// GENERATED FILE - do not edit by hand.
// Emoji data derived from the Unicode emoji-test.txt data (Unicode 17.0),
// https://unicode.org/Public/emoji/latest/emoji-test.txt
// Skin-tone and hair-component variants are omitted so the picker grid stays clean.

/// A single selectable emoji with its English name (used for search).
class HabitEmoji {
  const HabitEmoji(this.emoji, this.name);

  final String emoji;
  final String name;
}

/// A top-level emoji category shown as a chip in the picker.
class HabitEmojiCategory {
  const HabitEmojiCategory(this.label, this.emojis);

  final String label;
  final List<HabitEmoji> emojis;
}

/// Every standard emoji, grouped by category (file order preserved).
const List<HabitEmojiCategory> habitEmojiCategories = [
  HabitEmojiCategory("Smileys", [
    HabitEmoji("😀", "face smiling grinning face"),
    HabitEmoji("😃", "face smiling grinning face with big eyes"),
    HabitEmoji("😄", "face smiling grinning face with smiling eyes"),
    HabitEmoji("😁", "face smiling beaming face with smiling eyes"),
    HabitEmoji("😆", "face smiling grinning squinting face"),
    HabitEmoji("😅", "face smiling grinning face with sweat"),
    HabitEmoji("🤣", "face smiling rolling on the floor laughing"),
    HabitEmoji("😂", "face smiling face with tears of joy"),
    HabitEmoji("🙂", "face smiling slightly smiling face"),
    HabitEmoji("🙃", "face smiling upside-down face"),
    HabitEmoji("🫠", "face smiling melting face"),
    HabitEmoji("😉", "face smiling winking face"),
    HabitEmoji("😊", "face smiling smiling face with smiling eyes"),
    HabitEmoji("😇", "face smiling smiling face with halo"),
    HabitEmoji("🥰", "face affection smiling face with hearts"),
    HabitEmoji("😍", "face affection smiling face with heart-eyes"),
    HabitEmoji("🤩", "face affection star-struck"),
    HabitEmoji("😘", "face affection face blowing a kiss"),
    HabitEmoji("😗", "face affection kissing face"),
    HabitEmoji("☺️", "face affection smiling face"),
    HabitEmoji("😚", "face affection kissing face with closed eyes"),
    HabitEmoji("😙", "face affection kissing face with smiling eyes"),
    HabitEmoji("🥲", "face affection smiling face with tear"),
    HabitEmoji("😋", "face tongue face savoring food"),
    HabitEmoji("😛", "face tongue face with tongue"),
    HabitEmoji("😜", "face tongue winking face with tongue"),
    HabitEmoji("🤪", "face tongue zany face"),
    HabitEmoji("😝", "face tongue squinting face with tongue"),
    HabitEmoji("🤑", "face tongue money-mouth face"),
    HabitEmoji("🤗", "face hand smiling face with open hands"),
    HabitEmoji("🤭", "face hand face with hand over mouth"),
    HabitEmoji("🫢", "face hand face with open eyes and hand over mouth"),
    HabitEmoji("🫣", "face hand face with peeking eye"),
    HabitEmoji("🤫", "face hand shushing face"),
    HabitEmoji("🤔", "face hand thinking face"),
    HabitEmoji("🫡", "face hand saluting face"),
    HabitEmoji("🤐", "face neutral skeptical zipper-mouth face"),
    HabitEmoji("🤨", "face neutral skeptical face with raised eyebrow"),
    HabitEmoji("😐", "face neutral skeptical neutral face"),
    HabitEmoji("😑", "face neutral skeptical expressionless face"),
    HabitEmoji("😶", "face neutral skeptical face without mouth"),
    HabitEmoji("🫥", "face neutral skeptical dotted line face"),
    HabitEmoji("😶‍🌫️", "face neutral skeptical face in clouds"),
    HabitEmoji("😏", "face neutral skeptical smirking face"),
    HabitEmoji("😒", "face neutral skeptical unamused face"),
    HabitEmoji("🙄", "face neutral skeptical face with rolling eyes"),
    HabitEmoji("😬", "face neutral skeptical grimacing face"),
    HabitEmoji("😮‍💨", "face neutral skeptical face exhaling"),
    HabitEmoji("🤥", "face neutral skeptical lying face"),
    HabitEmoji("🫨", "face neutral skeptical shaking face"),
    HabitEmoji("🙂‍↔️", "face neutral skeptical head shaking horizontally"),
    HabitEmoji("🙂‍↕️", "face neutral skeptical head shaking vertically"),
    HabitEmoji("😌", "face sleepy relieved face"),
    HabitEmoji("😔", "face sleepy pensive face"),
    HabitEmoji("😪", "face sleepy sleepy face"),
    HabitEmoji("🤤", "face sleepy drooling face"),
    HabitEmoji("😴", "face sleepy sleeping face"),
    HabitEmoji("🫩", "face sleepy face with bags under eyes"),
    HabitEmoji("😷", "face unwell face with medical mask"),
    HabitEmoji("🤒", "face unwell face with thermometer"),
    HabitEmoji("🤕", "face unwell face with head-bandage"),
    HabitEmoji("🤢", "face unwell nauseated face"),
    HabitEmoji("🤮", "face unwell face vomiting"),
    HabitEmoji("🤧", "face unwell sneezing face"),
    HabitEmoji("🥵", "face unwell hot face"),
    HabitEmoji("🥶", "face unwell cold face"),
    HabitEmoji("🥴", "face unwell woozy face"),
    HabitEmoji("😵", "face unwell face with crossed-out eyes"),
    HabitEmoji("😵‍💫", "face unwell face with spiral eyes"),
    HabitEmoji("🤯", "face unwell exploding head"),
    HabitEmoji("🤠", "face hat cowboy hat face"),
    HabitEmoji("🥳", "face hat partying face"),
    HabitEmoji("🥸", "face hat disguised face"),
    HabitEmoji("😎", "face glasses smiling face with sunglasses"),
    HabitEmoji("🤓", "face glasses nerd face"),
    HabitEmoji("🧐", "face glasses face with monocle"),
    HabitEmoji("😕", "face concerned confused face"),
    HabitEmoji("🫤", "face concerned face with diagonal mouth"),
    HabitEmoji("😟", "face concerned worried face"),
    HabitEmoji("🙁", "face concerned slightly frowning face"),
    HabitEmoji("☹️", "face concerned frowning face"),
    HabitEmoji("😮", "face concerned face with open mouth"),
    HabitEmoji("😯", "face concerned hushed face"),
    HabitEmoji("😲", "face concerned astonished face"),
    HabitEmoji("😳", "face concerned flushed face"),
    HabitEmoji("🫪", "face concerned distorted face"),
    HabitEmoji("🥺", "face concerned pleading face"),
    HabitEmoji("🥹", "face concerned face holding back tears"),
    HabitEmoji("😦", "face concerned frowning face with open mouth"),
    HabitEmoji("😧", "face concerned anguished face"),
    HabitEmoji("😨", "face concerned fearful face"),
    HabitEmoji("😰", "face concerned anxious face with sweat"),
    HabitEmoji("😥", "face concerned sad but relieved face"),
    HabitEmoji("😢", "face concerned crying face"),
    HabitEmoji("😭", "face concerned loudly crying face"),
    HabitEmoji("😱", "face concerned face screaming in fear"),
    HabitEmoji("😖", "face concerned confounded face"),
    HabitEmoji("😣", "face concerned persevering face"),
    HabitEmoji("😞", "face concerned disappointed face"),
    HabitEmoji("😓", "face concerned downcast face with sweat"),
    HabitEmoji("😩", "face concerned weary face"),
    HabitEmoji("😫", "face concerned tired face"),
    HabitEmoji("🥱", "face concerned yawning face"),
    HabitEmoji("😤", "face negative face with steam from nose"),
    HabitEmoji("😡", "face negative enraged face"),
    HabitEmoji("😠", "face negative angry face"),
    HabitEmoji("🤬", "face negative face with symbols on mouth"),
    HabitEmoji("😈", "face negative smiling face with horns"),
    HabitEmoji("👿", "face negative angry face with horns"),
    HabitEmoji("💀", "face negative skull"),
    HabitEmoji("☠️", "face negative skull and crossbones"),
    HabitEmoji("💩", "face costume pile of poo"),
    HabitEmoji("🤡", "face costume clown face"),
    HabitEmoji("👹", "face costume ogre"),
    HabitEmoji("👺", "face costume goblin"),
    HabitEmoji("👻", "face costume ghost"),
    HabitEmoji("👽", "face costume alien"),
    HabitEmoji("👾", "face costume alien monster"),
    HabitEmoji("🤖", "face costume robot"),
    HabitEmoji("😺", "cat face grinning cat"),
    HabitEmoji("😸", "cat face grinning cat with smiling eyes"),
    HabitEmoji("😹", "cat face cat with tears of joy"),
    HabitEmoji("😻", "cat face smiling cat with heart-eyes"),
    HabitEmoji("😼", "cat face cat with wry smile"),
    HabitEmoji("😽", "cat face kissing cat"),
    HabitEmoji("🙀", "cat face weary cat"),
    HabitEmoji("😿", "cat face crying cat"),
    HabitEmoji("😾", "cat face pouting cat"),
    HabitEmoji("🙈", "monkey face see-no-evil monkey"),
    HabitEmoji("🙉", "monkey face hear-no-evil monkey"),
    HabitEmoji("🙊", "monkey face speak-no-evil monkey"),
    HabitEmoji("💌", "heart love letter"),
    HabitEmoji("💘", "heart heart with arrow"),
    HabitEmoji("💝", "heart heart with ribbon"),
    HabitEmoji("💖", "heart sparkling heart"),
    HabitEmoji("💗", "heart growing heart"),
    HabitEmoji("💓", "heart beating heart"),
    HabitEmoji("💞", "heart revolving hearts"),
    HabitEmoji("💕", "heart two hearts"),
    HabitEmoji("💟", "heart heart decoration"),
    HabitEmoji("❣️", "heart heart exclamation"),
    HabitEmoji("💔", "heart broken heart"),
    HabitEmoji("❤️‍🔥", "heart heart on fire"),
    HabitEmoji("❤️‍🩹", "heart mending heart"),
    HabitEmoji("❤️", "heart red heart"),
    HabitEmoji("🩷", "heart pink heart"),
    HabitEmoji("🧡", "heart orange heart"),
    HabitEmoji("💛", "heart yellow heart"),
    HabitEmoji("💚", "heart green heart"),
    HabitEmoji("💙", "heart blue heart"),
    HabitEmoji("🩵", "heart light blue heart"),
    HabitEmoji("💜", "heart purple heart"),
    HabitEmoji("🤎", "heart brown heart"),
    HabitEmoji("🖤", "heart black heart"),
    HabitEmoji("🩶", "heart grey heart"),
    HabitEmoji("🤍", "heart white heart"),
    HabitEmoji("💋", "emotion kiss mark"),
    HabitEmoji("💯", "emotion hundred points"),
    HabitEmoji("💢", "emotion anger symbol"),
    HabitEmoji("🫯", "emotion fight cloud"),
    HabitEmoji("💥", "emotion collision"),
    HabitEmoji("💫", "emotion dizzy"),
    HabitEmoji("💦", "emotion sweat droplets"),
    HabitEmoji("💨", "emotion dashing away"),
    HabitEmoji("🕳️", "emotion hole"),
    HabitEmoji("💬", "emotion speech balloon"),
    HabitEmoji("👁️‍🗨️", "emotion eye in speech bubble"),
    HabitEmoji("🗨️", "emotion left speech bubble"),
    HabitEmoji("🗯️", "emotion right anger bubble"),
    HabitEmoji("💭", "emotion thought balloon"),
    HabitEmoji("💤", "emotion ZZZ"),
  ]),
  HabitEmojiCategory("People", [
    HabitEmoji("👋", "hand fingers open waving hand"),
    HabitEmoji("🤚", "hand fingers open raised back of hand"),
    HabitEmoji("🖐️", "hand fingers open hand with fingers splayed"),
    HabitEmoji("✋", "hand fingers open raised hand"),
    HabitEmoji("🖖", "hand fingers open vulcan salute"),
    HabitEmoji("🫱", "hand fingers open rightwards hand"),
    HabitEmoji("🫲", "hand fingers open leftwards hand"),
    HabitEmoji("🫳", "hand fingers open palm down hand"),
    HabitEmoji("🫴", "hand fingers open palm up hand"),
    HabitEmoji("🫷", "hand fingers open leftwards pushing hand"),
    HabitEmoji("🫸", "hand fingers open rightwards pushing hand"),
    HabitEmoji("👌", "hand fingers partial OK hand"),
    HabitEmoji("🤌", "hand fingers partial pinched fingers"),
    HabitEmoji("🤏", "hand fingers partial pinching hand"),
    HabitEmoji("✌️", "hand fingers partial victory hand"),
    HabitEmoji("🤞", "hand fingers partial crossed fingers"),
    HabitEmoji(
        "🫰", "hand fingers partial hand with index finger and thumb crossed"),
    HabitEmoji("🤟", "hand fingers partial love-you gesture"),
    HabitEmoji("🤘", "hand fingers partial sign of the horns"),
    HabitEmoji("🤙", "hand fingers partial call me hand"),
    HabitEmoji("👈", "hand single finger backhand index pointing left"),
    HabitEmoji("👉", "hand single finger backhand index pointing right"),
    HabitEmoji("👆", "hand single finger backhand index pointing up"),
    HabitEmoji("🖕", "hand single finger middle finger"),
    HabitEmoji("👇", "hand single finger backhand index pointing down"),
    HabitEmoji("☝️", "hand single finger index pointing up"),
    HabitEmoji("🫵", "hand single finger index pointing at the viewer"),
    HabitEmoji("👍", "hand fingers closed thumbs up"),
    HabitEmoji("👎", "hand fingers closed thumbs down"),
    HabitEmoji("✊", "hand fingers closed raised fist"),
    HabitEmoji("👊", "hand fingers closed oncoming fist"),
    HabitEmoji("🤛", "hand fingers closed left-facing fist"),
    HabitEmoji("🤜", "hand fingers closed right-facing fist"),
    HabitEmoji("👏", "hands clapping hands"),
    HabitEmoji("🙌", "hands raising hands"),
    HabitEmoji("🫶", "hands heart hands"),
    HabitEmoji("👐", "hands open hands"),
    HabitEmoji("🤲", "hands palms up together"),
    HabitEmoji("🤝", "hands handshake"),
    HabitEmoji("🙏", "hands folded hands"),
    HabitEmoji("✍️", "hand prop writing hand"),
    HabitEmoji("💅", "hand prop nail polish"),
    HabitEmoji("🤳", "hand prop selfie"),
    HabitEmoji("💪", "body parts flexed biceps"),
    HabitEmoji("🦾", "body parts mechanical arm"),
    HabitEmoji("🦿", "body parts mechanical leg"),
    HabitEmoji("🦵", "body parts leg"),
    HabitEmoji("🦶", "body parts foot"),
    HabitEmoji("👂", "body parts ear"),
    HabitEmoji("🦻", "body parts ear with hearing aid"),
    HabitEmoji("👃", "body parts nose"),
    HabitEmoji("🧠", "body parts brain"),
    HabitEmoji("🫀", "body parts anatomical heart"),
    HabitEmoji("🫁", "body parts lungs"),
    HabitEmoji("🦷", "body parts tooth"),
    HabitEmoji("🦴", "body parts bone"),
    HabitEmoji("👀", "body parts eyes"),
    HabitEmoji("👁️", "body parts eye"),
    HabitEmoji("👅", "body parts tongue"),
    HabitEmoji("👄", "body parts mouth"),
    HabitEmoji("🫦", "body parts biting lip"),
    HabitEmoji("👶", "person baby"),
    HabitEmoji("🧒", "person child"),
    HabitEmoji("👦", "person boy"),
    HabitEmoji("👧", "person girl"),
    HabitEmoji("🧑", "person person"),
    HabitEmoji("👱", "person person: blond hair"),
    HabitEmoji("👨", "person man"),
    HabitEmoji("🧔", "person person: beard"),
    HabitEmoji("🧔‍♂️", "person man: beard"),
    HabitEmoji("🧔‍♀️", "person woman: beard"),
    HabitEmoji("👩", "person woman"),
    HabitEmoji("👱‍♀️", "person woman: blond hair"),
    HabitEmoji("👱‍♂️", "person man: blond hair"),
    HabitEmoji("🧓", "person older person"),
    HabitEmoji("👴", "person old man"),
    HabitEmoji("👵", "person old woman"),
    HabitEmoji("🙍", "person gesture person frowning"),
    HabitEmoji("🙍‍♂️", "person gesture man frowning"),
    HabitEmoji("🙍‍♀️", "person gesture woman frowning"),
    HabitEmoji("🙎", "person gesture person pouting"),
    HabitEmoji("🙎‍♂️", "person gesture man pouting"),
    HabitEmoji("🙎‍♀️", "person gesture woman pouting"),
    HabitEmoji("🙅", "person gesture person gesturing NO"),
    HabitEmoji("🙅‍♂️", "person gesture man gesturing NO"),
    HabitEmoji("🙅‍♀️", "person gesture woman gesturing NO"),
    HabitEmoji("🙆", "person gesture person gesturing OK"),
    HabitEmoji("🙆‍♂️", "person gesture man gesturing OK"),
    HabitEmoji("🙆‍♀️", "person gesture woman gesturing OK"),
    HabitEmoji("💁", "person gesture person tipping hand"),
    HabitEmoji("💁‍♂️", "person gesture man tipping hand"),
    HabitEmoji("💁‍♀️", "person gesture woman tipping hand"),
    HabitEmoji("🙋", "person gesture person raising hand"),
    HabitEmoji("🙋‍♂️", "person gesture man raising hand"),
    HabitEmoji("🙋‍♀️", "person gesture woman raising hand"),
    HabitEmoji("🧏", "person gesture deaf person"),
    HabitEmoji("🧏‍♂️", "person gesture deaf man"),
    HabitEmoji("🧏‍♀️", "person gesture deaf woman"),
    HabitEmoji("🙇", "person gesture person bowing"),
    HabitEmoji("🙇‍♂️", "person gesture man bowing"),
    HabitEmoji("🙇‍♀️", "person gesture woman bowing"),
    HabitEmoji("🤦", "person gesture person facepalming"),
    HabitEmoji("🤦‍♂️", "person gesture man facepalming"),
    HabitEmoji("🤦‍♀️", "person gesture woman facepalming"),
    HabitEmoji("🤷", "person gesture person shrugging"),
    HabitEmoji("🤷‍♂️", "person gesture man shrugging"),
    HabitEmoji("🤷‍♀️", "person gesture woman shrugging"),
    HabitEmoji("🧑‍⚕️", "person role health worker"),
    HabitEmoji("👨‍⚕️", "person role man health worker"),
    HabitEmoji("👩‍⚕️", "person role woman health worker"),
    HabitEmoji("🧑‍🎓", "person role student"),
    HabitEmoji("👨‍🎓", "person role man student"),
    HabitEmoji("👩‍🎓", "person role woman student"),
    HabitEmoji("🧑‍🏫", "person role teacher"),
    HabitEmoji("👨‍🏫", "person role man teacher"),
    HabitEmoji("👩‍🏫", "person role woman teacher"),
    HabitEmoji("🧑‍⚖️", "person role judge"),
    HabitEmoji("👨‍⚖️", "person role man judge"),
    HabitEmoji("👩‍⚖️", "person role woman judge"),
    HabitEmoji("🧑‍🌾", "person role farmer"),
    HabitEmoji("👨‍🌾", "person role man farmer"),
    HabitEmoji("👩‍🌾", "person role woman farmer"),
    HabitEmoji("🧑‍🍳", "person role cook"),
    HabitEmoji("👨‍🍳", "person role man cook"),
    HabitEmoji("👩‍🍳", "person role woman cook"),
    HabitEmoji("🧑‍🔧", "person role mechanic"),
    HabitEmoji("👨‍🔧", "person role man mechanic"),
    HabitEmoji("👩‍🔧", "person role woman mechanic"),
    HabitEmoji("🧑‍🏭", "person role factory worker"),
    HabitEmoji("👨‍🏭", "person role man factory worker"),
    HabitEmoji("👩‍🏭", "person role woman factory worker"),
    HabitEmoji("🧑‍💼", "person role office worker"),
    HabitEmoji("👨‍💼", "person role man office worker"),
    HabitEmoji("👩‍💼", "person role woman office worker"),
    HabitEmoji("🧑‍🔬", "person role scientist"),
    HabitEmoji("👨‍🔬", "person role man scientist"),
    HabitEmoji("👩‍🔬", "person role woman scientist"),
    HabitEmoji("🧑‍💻", "person role technologist"),
    HabitEmoji("👨‍💻", "person role man technologist"),
    HabitEmoji("👩‍💻", "person role woman technologist"),
    HabitEmoji("🧑‍🎤", "person role singer"),
    HabitEmoji("👨‍🎤", "person role man singer"),
    HabitEmoji("👩‍🎤", "person role woman singer"),
    HabitEmoji("🧑‍🎨", "person role artist"),
    HabitEmoji("👨‍🎨", "person role man artist"),
    HabitEmoji("👩‍🎨", "person role woman artist"),
    HabitEmoji("🧑‍✈️", "person role pilot"),
    HabitEmoji("👨‍✈️", "person role man pilot"),
    HabitEmoji("👩‍✈️", "person role woman pilot"),
    HabitEmoji("🧑‍🚀", "person role astronaut"),
    HabitEmoji("👨‍🚀", "person role man astronaut"),
    HabitEmoji("👩‍🚀", "person role woman astronaut"),
    HabitEmoji("🧑‍🚒", "person role firefighter"),
    HabitEmoji("👨‍🚒", "person role man firefighter"),
    HabitEmoji("👩‍🚒", "person role woman firefighter"),
    HabitEmoji("👮", "person role police officer"),
    HabitEmoji("👮‍♂️", "person role man police officer"),
    HabitEmoji("👮‍♀️", "person role woman police officer"),
    HabitEmoji("🕵️", "person role detective"),
    HabitEmoji("🕵️‍♂️", "person role man detective"),
    HabitEmoji("🕵️‍♀️", "person role woman detective"),
    HabitEmoji("💂", "person role guard"),
    HabitEmoji("💂‍♂️", "person role man guard"),
    HabitEmoji("💂‍♀️", "person role woman guard"),
    HabitEmoji("🥷", "person role ninja"),
    HabitEmoji("👷", "person role construction worker"),
    HabitEmoji("👷‍♂️", "person role man construction worker"),
    HabitEmoji("👷‍♀️", "person role woman construction worker"),
    HabitEmoji("🫅", "person role person with crown"),
    HabitEmoji("🤴", "person role prince"),
    HabitEmoji("👸", "person role princess"),
    HabitEmoji("👳", "person role person wearing turban"),
    HabitEmoji("👳‍♂️", "person role man wearing turban"),
    HabitEmoji("👳‍♀️", "person role woman wearing turban"),
    HabitEmoji("👲", "person role person with skullcap"),
    HabitEmoji("🧕", "person role woman with headscarf"),
    HabitEmoji("🤵", "person role person in tuxedo"),
    HabitEmoji("🤵‍♂️", "person role man in tuxedo"),
    HabitEmoji("🤵‍♀️", "person role woman in tuxedo"),
    HabitEmoji("👰", "person role person with veil"),
    HabitEmoji("👰‍♂️", "person role man with veil"),
    HabitEmoji("👰‍♀️", "person role woman with veil"),
    HabitEmoji("🤰", "person role pregnant woman"),
    HabitEmoji("🫃", "person role pregnant man"),
    HabitEmoji("🫄", "person role pregnant person"),
    HabitEmoji("🤱", "person role breast-feeding"),
    HabitEmoji("👩‍🍼", "person role woman feeding baby"),
    HabitEmoji("👨‍🍼", "person role man feeding baby"),
    HabitEmoji("🧑‍🍼", "person role person feeding baby"),
    HabitEmoji("👼", "person fantasy baby angel"),
    HabitEmoji("🎅", "person fantasy Santa Claus"),
    HabitEmoji("🤶", "person fantasy Mrs. Claus"),
    HabitEmoji("🧑‍🎄", "person fantasy Mx Claus"),
    HabitEmoji("🦸", "person fantasy superhero"),
    HabitEmoji("🦸‍♂️", "person fantasy man superhero"),
    HabitEmoji("🦸‍♀️", "person fantasy woman superhero"),
    HabitEmoji("🦹", "person fantasy supervillain"),
    HabitEmoji("🦹‍♂️", "person fantasy man supervillain"),
    HabitEmoji("🦹‍♀️", "person fantasy woman supervillain"),
    HabitEmoji("🧙", "person fantasy mage"),
    HabitEmoji("🧙‍♂️", "person fantasy man mage"),
    HabitEmoji("🧙‍♀️", "person fantasy woman mage"),
    HabitEmoji("🧚", "person fantasy fairy"),
    HabitEmoji("🧚‍♂️", "person fantasy man fairy"),
    HabitEmoji("🧚‍♀️", "person fantasy woman fairy"),
    HabitEmoji("🧛", "person fantasy vampire"),
    HabitEmoji("🧛‍♂️", "person fantasy man vampire"),
    HabitEmoji("🧛‍♀️", "person fantasy woman vampire"),
    HabitEmoji("🧜", "person fantasy merperson"),
    HabitEmoji("🧜‍♂️", "person fantasy merman"),
    HabitEmoji("🧜‍♀️", "person fantasy mermaid"),
    HabitEmoji("🧝", "person fantasy elf"),
    HabitEmoji("🧝‍♂️", "person fantasy man elf"),
    HabitEmoji("🧝‍♀️", "person fantasy woman elf"),
    HabitEmoji("🧞", "person fantasy genie"),
    HabitEmoji("🧞‍♂️", "person fantasy man genie"),
    HabitEmoji("🧞‍♀️", "person fantasy woman genie"),
    HabitEmoji("🧟", "person fantasy zombie"),
    HabitEmoji("🧟‍♂️", "person fantasy man zombie"),
    HabitEmoji("🧟‍♀️", "person fantasy woman zombie"),
    HabitEmoji("🧌", "person fantasy troll"),
    HabitEmoji("🫈", "person fantasy hairy creature"),
    HabitEmoji("💆", "person activity person getting massage"),
    HabitEmoji("💆‍♂️", "person activity man getting massage"),
    HabitEmoji("💆‍♀️", "person activity woman getting massage"),
    HabitEmoji("💇", "person activity person getting haircut"),
    HabitEmoji("💇‍♂️", "person activity man getting haircut"),
    HabitEmoji("💇‍♀️", "person activity woman getting haircut"),
    HabitEmoji("🚶", "person activity person walking"),
    HabitEmoji("🚶‍♂️", "person activity man walking"),
    HabitEmoji("🚶‍♀️", "person activity woman walking"),
    HabitEmoji("🚶‍➡️", "person activity person walking facing right"),
    HabitEmoji("🚶‍♀️‍➡️", "person activity woman walking facing right"),
    HabitEmoji("🚶‍♂️‍➡️", "person activity man walking facing right"),
    HabitEmoji("🧍", "person activity person standing"),
    HabitEmoji("🧍‍♂️", "person activity man standing"),
    HabitEmoji("🧍‍♀️", "person activity woman standing"),
    HabitEmoji("🧎", "person activity person kneeling"),
    HabitEmoji("🧎‍♂️", "person activity man kneeling"),
    HabitEmoji("🧎‍♀️", "person activity woman kneeling"),
    HabitEmoji("🧎‍➡️", "person activity person kneeling facing right"),
    HabitEmoji("🧎‍♀️‍➡️", "person activity woman kneeling facing right"),
    HabitEmoji("🧎‍♂️‍➡️", "person activity man kneeling facing right"),
    HabitEmoji("🧑‍🦯", "person activity person with white cane"),
    HabitEmoji(
        "🧑‍🦯‍➡️", "person activity person with white cane facing right"),
    HabitEmoji("👨‍🦯", "person activity man with white cane"),
    HabitEmoji("👨‍🦯‍➡️", "person activity man with white cane facing right"),
    HabitEmoji("👩‍🦯", "person activity woman with white cane"),
    HabitEmoji(
        "👩‍🦯‍➡️", "person activity woman with white cane facing right"),
    HabitEmoji("🧑‍🦼", "person activity person in motorized wheelchair"),
    HabitEmoji("🧑‍🦼‍➡️",
        "person activity person in motorized wheelchair facing right"),
    HabitEmoji("👨‍🦼", "person activity man in motorized wheelchair"),
    HabitEmoji(
        "👨‍🦼‍➡️", "person activity man in motorized wheelchair facing right"),
    HabitEmoji("👩‍🦼", "person activity woman in motorized wheelchair"),
    HabitEmoji("👩‍🦼‍➡️",
        "person activity woman in motorized wheelchair facing right"),
    HabitEmoji("🧑‍🦽", "person activity person in manual wheelchair"),
    HabitEmoji(
        "🧑‍🦽‍➡️", "person activity person in manual wheelchair facing right"),
    HabitEmoji("👨‍🦽", "person activity man in manual wheelchair"),
    HabitEmoji(
        "👨‍🦽‍➡️", "person activity man in manual wheelchair facing right"),
    HabitEmoji("👩‍🦽", "person activity woman in manual wheelchair"),
    HabitEmoji(
        "👩‍🦽‍➡️", "person activity woman in manual wheelchair facing right"),
    HabitEmoji("🏃", "person activity person running"),
    HabitEmoji("🏃‍♂️", "person activity man running"),
    HabitEmoji("🏃‍♀️", "person activity woman running"),
    HabitEmoji("🏃‍➡️", "person activity person running facing right"),
    HabitEmoji("🏃‍♀️‍➡️", "person activity woman running facing right"),
    HabitEmoji("🏃‍♂️‍➡️", "person activity man running facing right"),
    HabitEmoji("🧑‍🩰", "person activity ballet dancer"),
    HabitEmoji("💃", "person activity woman dancing"),
    HabitEmoji("🕺", "person activity man dancing"),
    HabitEmoji("🕴️", "person activity person in suit levitating"),
    HabitEmoji("👯", "person activity people with bunny ears"),
    HabitEmoji("👯‍♂️", "person activity men with bunny ears"),
    HabitEmoji("👯‍♀️", "person activity women with bunny ears"),
    HabitEmoji("🧖", "person activity person in steamy room"),
    HabitEmoji("🧖‍♂️", "person activity man in steamy room"),
    HabitEmoji("🧖‍♀️", "person activity woman in steamy room"),
    HabitEmoji("🧗", "person activity person climbing"),
    HabitEmoji("🧗‍♂️", "person activity man climbing"),
    HabitEmoji("🧗‍♀️", "person activity woman climbing"),
    HabitEmoji("🤺", "person sport person fencing"),
    HabitEmoji("🏇", "person sport horse racing"),
    HabitEmoji("⛷️", "person sport skier"),
    HabitEmoji("🏂", "person sport snowboarder"),
    HabitEmoji("🏌️", "person sport person golfing"),
    HabitEmoji("🏌️‍♂️", "person sport man golfing"),
    HabitEmoji("🏌️‍♀️", "person sport woman golfing"),
    HabitEmoji("🏄", "person sport person surfing"),
    HabitEmoji("🏄‍♂️", "person sport man surfing"),
    HabitEmoji("🏄‍♀️", "person sport woman surfing"),
    HabitEmoji("🚣", "person sport person rowing boat"),
    HabitEmoji("🚣‍♂️", "person sport man rowing boat"),
    HabitEmoji("🚣‍♀️", "person sport woman rowing boat"),
    HabitEmoji("🏊", "person sport person swimming"),
    HabitEmoji("🏊‍♂️", "person sport man swimming"),
    HabitEmoji("🏊‍♀️", "person sport woman swimming"),
    HabitEmoji("⛹️", "person sport person bouncing ball"),
    HabitEmoji("⛹️‍♂️", "person sport man bouncing ball"),
    HabitEmoji("⛹️‍♀️", "person sport woman bouncing ball"),
    HabitEmoji("🏋️", "person sport person lifting weights"),
    HabitEmoji("🏋️‍♂️", "person sport man lifting weights"),
    HabitEmoji("🏋️‍♀️", "person sport woman lifting weights"),
    HabitEmoji("🚴", "person sport person biking"),
    HabitEmoji("🚴‍♂️", "person sport man biking"),
    HabitEmoji("🚴‍♀️", "person sport woman biking"),
    HabitEmoji("🚵", "person sport person mountain biking"),
    HabitEmoji("🚵‍♂️", "person sport man mountain biking"),
    HabitEmoji("🚵‍♀️", "person sport woman mountain biking"),
    HabitEmoji("🤸", "person sport person cartwheeling"),
    HabitEmoji("🤸‍♂️", "person sport man cartwheeling"),
    HabitEmoji("🤸‍♀️", "person sport woman cartwheeling"),
    HabitEmoji("🤼", "person sport people wrestling"),
    HabitEmoji("🤼‍♂️", "person sport men wrestling"),
    HabitEmoji("🤼‍♀️", "person sport women wrestling"),
    HabitEmoji("🤽", "person sport person playing water polo"),
    HabitEmoji("🤽‍♂️", "person sport man playing water polo"),
    HabitEmoji("🤽‍♀️", "person sport woman playing water polo"),
    HabitEmoji("🤾", "person sport person playing handball"),
    HabitEmoji("🤾‍♂️", "person sport man playing handball"),
    HabitEmoji("🤾‍♀️", "person sport woman playing handball"),
    HabitEmoji("🤹", "person sport person juggling"),
    HabitEmoji("🤹‍♂️", "person sport man juggling"),
    HabitEmoji("🤹‍♀️", "person sport woman juggling"),
    HabitEmoji("🧘", "person resting person in lotus position"),
    HabitEmoji("🧘‍♂️", "person resting man in lotus position"),
    HabitEmoji("🧘‍♀️", "person resting woman in lotus position"),
    HabitEmoji("🛀", "person resting person taking bath"),
    HabitEmoji("🛌", "person resting person in bed"),
    HabitEmoji("🧑‍🤝‍🧑", "family people holding hands"),
    HabitEmoji("👭", "family women holding hands"),
    HabitEmoji("👫", "family woman and man holding hands"),
    HabitEmoji("👬", "family men holding hands"),
    HabitEmoji("💏", "family kiss"),
    HabitEmoji("👩‍❤️‍💋‍👨", "family kiss: woman, man"),
    HabitEmoji("👨‍❤️‍💋‍👨", "family kiss: man, man"),
    HabitEmoji("👩‍❤️‍💋‍👩", "family kiss: woman, woman"),
    HabitEmoji("💑", "family couple with heart"),
    HabitEmoji("👩‍❤️‍👨", "family couple with heart: woman, man"),
    HabitEmoji("👨‍❤️‍👨", "family couple with heart: man, man"),
    HabitEmoji("👩‍❤️‍👩", "family couple with heart: woman, woman"),
    HabitEmoji("👨‍👩‍👦", "family family: man, woman, boy"),
    HabitEmoji("👨‍👩‍👧", "family family: man, woman, girl"),
    HabitEmoji("👨‍👩‍👧‍👦", "family family: man, woman, girl, boy"),
    HabitEmoji("👨‍👩‍👦‍👦", "family family: man, woman, boy, boy"),
    HabitEmoji("👨‍👩‍👧‍👧", "family family: man, woman, girl, girl"),
    HabitEmoji("👨‍👨‍👦", "family family: man, man, boy"),
    HabitEmoji("👨‍👨‍👧", "family family: man, man, girl"),
    HabitEmoji("👨‍👨‍👧‍👦", "family family: man, man, girl, boy"),
    HabitEmoji("👨‍👨‍👦‍👦", "family family: man, man, boy, boy"),
    HabitEmoji("👨‍👨‍👧‍👧", "family family: man, man, girl, girl"),
    HabitEmoji("👩‍👩‍👦", "family family: woman, woman, boy"),
    HabitEmoji("👩‍👩‍👧", "family family: woman, woman, girl"),
    HabitEmoji("👩‍👩‍👧‍👦", "family family: woman, woman, girl, boy"),
    HabitEmoji("👩‍👩‍👦‍👦", "family family: woman, woman, boy, boy"),
    HabitEmoji("👩‍👩‍👧‍👧", "family family: woman, woman, girl, girl"),
    HabitEmoji("👨‍👦", "family family: man, boy"),
    HabitEmoji("👨‍👦‍👦", "family family: man, boy, boy"),
    HabitEmoji("👨‍👧", "family family: man, girl"),
    HabitEmoji("👨‍👧‍👦", "family family: man, girl, boy"),
    HabitEmoji("👨‍👧‍👧", "family family: man, girl, girl"),
    HabitEmoji("👩‍👦", "family family: woman, boy"),
    HabitEmoji("👩‍👦‍👦", "family family: woman, boy, boy"),
    HabitEmoji("👩‍👧", "family family: woman, girl"),
    HabitEmoji("👩‍👧‍👦", "family family: woman, girl, boy"),
    HabitEmoji("👩‍👧‍👧", "family family: woman, girl, girl"),
    HabitEmoji("🗣️", "person symbol speaking head"),
    HabitEmoji("👤", "person symbol bust in silhouette"),
    HabitEmoji("👥", "person symbol busts in silhouette"),
    HabitEmoji("🫂", "person symbol people hugging"),
    HabitEmoji("👪", "person symbol family"),
    HabitEmoji("🧑‍🧑‍🧒", "person symbol family: adult, adult, child"),
    HabitEmoji(
        "🧑‍🧑‍🧒‍🧒", "person symbol family: adult, adult, child, child"),
    HabitEmoji("🧑‍🧒", "person symbol family: adult, child"),
    HabitEmoji("🧑‍🧒‍🧒", "person symbol family: adult, child, child"),
    HabitEmoji("👣", "person symbol footprints"),
    HabitEmoji("🫆", "person symbol fingerprint"),
  ]),
  HabitEmojiCategory("Animals", [
    HabitEmoji("🐵", "animal mammal monkey face"),
    HabitEmoji("🐒", "animal mammal monkey"),
    HabitEmoji("🦍", "animal mammal gorilla"),
    HabitEmoji("🦧", "animal mammal orangutan"),
    HabitEmoji("🐶", "animal mammal dog face"),
    HabitEmoji("🐕", "animal mammal dog"),
    HabitEmoji("🦮", "animal mammal guide dog"),
    HabitEmoji("🐕‍🦺", "animal mammal service dog"),
    HabitEmoji("🐩", "animal mammal poodle"),
    HabitEmoji("🐺", "animal mammal wolf"),
    HabitEmoji("🦊", "animal mammal fox"),
    HabitEmoji("🦝", "animal mammal raccoon"),
    HabitEmoji("🐱", "animal mammal cat face"),
    HabitEmoji("🐈", "animal mammal cat"),
    HabitEmoji("🐈‍⬛", "animal mammal black cat"),
    HabitEmoji("🦁", "animal mammal lion"),
    HabitEmoji("🐯", "animal mammal tiger face"),
    HabitEmoji("🐅", "animal mammal tiger"),
    HabitEmoji("🐆", "animal mammal leopard"),
    HabitEmoji("🐴", "animal mammal horse face"),
    HabitEmoji("🫎", "animal mammal moose"),
    HabitEmoji("🫏", "animal mammal donkey"),
    HabitEmoji("🐎", "animal mammal horse"),
    HabitEmoji("🦄", "animal mammal unicorn"),
    HabitEmoji("🦓", "animal mammal zebra"),
    HabitEmoji("🦌", "animal mammal deer"),
    HabitEmoji("🦬", "animal mammal bison"),
    HabitEmoji("🐮", "animal mammal cow face"),
    HabitEmoji("🐂", "animal mammal ox"),
    HabitEmoji("🐃", "animal mammal water buffalo"),
    HabitEmoji("🐄", "animal mammal cow"),
    HabitEmoji("🐷", "animal mammal pig face"),
    HabitEmoji("🐖", "animal mammal pig"),
    HabitEmoji("🐗", "animal mammal boar"),
    HabitEmoji("🐽", "animal mammal pig nose"),
    HabitEmoji("🐏", "animal mammal ram"),
    HabitEmoji("🐑", "animal mammal ewe"),
    HabitEmoji("🐐", "animal mammal goat"),
    HabitEmoji("🐪", "animal mammal camel"),
    HabitEmoji("🐫", "animal mammal two-hump camel"),
    HabitEmoji("🦙", "animal mammal llama"),
    HabitEmoji("🦒", "animal mammal giraffe"),
    HabitEmoji("🐘", "animal mammal elephant"),
    HabitEmoji("🦣", "animal mammal mammoth"),
    HabitEmoji("🦏", "animal mammal rhinoceros"),
    HabitEmoji("🦛", "animal mammal hippopotamus"),
    HabitEmoji("🐭", "animal mammal mouse face"),
    HabitEmoji("🐁", "animal mammal mouse"),
    HabitEmoji("🐀", "animal mammal rat"),
    HabitEmoji("🐹", "animal mammal hamster"),
    HabitEmoji("🐰", "animal mammal rabbit face"),
    HabitEmoji("🐇", "animal mammal rabbit"),
    HabitEmoji("🐿️", "animal mammal chipmunk"),
    HabitEmoji("🦫", "animal mammal beaver"),
    HabitEmoji("🦔", "animal mammal hedgehog"),
    HabitEmoji("🦇", "animal mammal bat"),
    HabitEmoji("🐻", "animal mammal bear"),
    HabitEmoji("🐻‍❄️", "animal mammal polar bear"),
    HabitEmoji("🐨", "animal mammal koala"),
    HabitEmoji("🐼", "animal mammal panda"),
    HabitEmoji("🦥", "animal mammal sloth"),
    HabitEmoji("🦦", "animal mammal otter"),
    HabitEmoji("🦨", "animal mammal skunk"),
    HabitEmoji("🦘", "animal mammal kangaroo"),
    HabitEmoji("🦡", "animal mammal badger"),
    HabitEmoji("🐾", "animal mammal paw prints"),
    HabitEmoji("🦃", "animal bird turkey"),
    HabitEmoji("🐔", "animal bird chicken"),
    HabitEmoji("🐓", "animal bird rooster"),
    HabitEmoji("🐣", "animal bird hatching chick"),
    HabitEmoji("🐤", "animal bird baby chick"),
    HabitEmoji("🐥", "animal bird front-facing baby chick"),
    HabitEmoji("🐦", "animal bird bird"),
    HabitEmoji("🐧", "animal bird penguin"),
    HabitEmoji("🕊️", "animal bird dove"),
    HabitEmoji("🦅", "animal bird eagle"),
    HabitEmoji("🦆", "animal bird duck"),
    HabitEmoji("🦢", "animal bird swan"),
    HabitEmoji("🦉", "animal bird owl"),
    HabitEmoji("🦤", "animal bird dodo"),
    HabitEmoji("🪶", "animal bird feather"),
    HabitEmoji("🦩", "animal bird flamingo"),
    HabitEmoji("🦚", "animal bird peacock"),
    HabitEmoji("🦜", "animal bird parrot"),
    HabitEmoji("🪽", "animal bird wing"),
    HabitEmoji("🐦‍⬛", "animal bird black bird"),
    HabitEmoji("🪿", "animal bird goose"),
    HabitEmoji("🐦‍🔥", "animal bird phoenix"),
    HabitEmoji("🐸", "animal amphibian frog"),
    HabitEmoji("🐊", "animal reptile crocodile"),
    HabitEmoji("🐢", "animal reptile turtle"),
    HabitEmoji("🦎", "animal reptile lizard"),
    HabitEmoji("🐍", "animal reptile snake"),
    HabitEmoji("🐲", "animal reptile dragon face"),
    HabitEmoji("🐉", "animal reptile dragon"),
    HabitEmoji("🦕", "animal reptile sauropod"),
    HabitEmoji("🦖", "animal reptile T-Rex"),
    HabitEmoji("🐳", "animal marine spouting whale"),
    HabitEmoji("🐋", "animal marine whale"),
    HabitEmoji("🐬", "animal marine dolphin"),
    HabitEmoji("🫍", "animal marine orca"),
    HabitEmoji("🦭", "animal marine seal"),
    HabitEmoji("🐟", "animal marine fish"),
    HabitEmoji("🐠", "animal marine tropical fish"),
    HabitEmoji("🐡", "animal marine blowfish"),
    HabitEmoji("🦈", "animal marine shark"),
    HabitEmoji("🐙", "animal marine octopus"),
    HabitEmoji("🐚", "animal marine spiral shell"),
    HabitEmoji("🪸", "animal marine coral"),
    HabitEmoji("🪼", "animal marine jellyfish"),
    HabitEmoji("🦀", "animal marine crab"),
    HabitEmoji("🦞", "animal marine lobster"),
    HabitEmoji("🦐", "animal marine shrimp"),
    HabitEmoji("🦑", "animal marine squid"),
    HabitEmoji("🦪", "animal marine oyster"),
    HabitEmoji("🐌", "animal bug snail"),
    HabitEmoji("🦋", "animal bug butterfly"),
    HabitEmoji("🐛", "animal bug bug"),
    HabitEmoji("🐜", "animal bug ant"),
    HabitEmoji("🐝", "animal bug honeybee"),
    HabitEmoji("🪲", "animal bug beetle"),
    HabitEmoji("🐞", "animal bug lady beetle"),
    HabitEmoji("🦗", "animal bug cricket"),
    HabitEmoji("🪳", "animal bug cockroach"),
    HabitEmoji("🕷️", "animal bug spider"),
    HabitEmoji("🕸️", "animal bug spider web"),
    HabitEmoji("🦂", "animal bug scorpion"),
    HabitEmoji("🦟", "animal bug mosquito"),
    HabitEmoji("🪰", "animal bug fly"),
    HabitEmoji("🪱", "animal bug worm"),
    HabitEmoji("🦠", "animal bug microbe"),
    HabitEmoji("💐", "plant flower bouquet"),
    HabitEmoji("🌸", "plant flower cherry blossom"),
    HabitEmoji("💮", "plant flower white flower"),
    HabitEmoji("🪷", "plant flower lotus"),
    HabitEmoji("🏵️", "plant flower rosette"),
    HabitEmoji("🌹", "plant flower rose"),
    HabitEmoji("🥀", "plant flower wilted flower"),
    HabitEmoji("🌺", "plant flower hibiscus"),
    HabitEmoji("🌻", "plant flower sunflower"),
    HabitEmoji("🌼", "plant flower blossom"),
    HabitEmoji("🌷", "plant flower tulip"),
    HabitEmoji("🪻", "plant flower hyacinth"),
    HabitEmoji("🌱", "plant other seedling"),
    HabitEmoji("🪴", "plant other potted plant"),
    HabitEmoji("🌲", "plant other evergreen tree"),
    HabitEmoji("🌳", "plant other deciduous tree"),
    HabitEmoji("🌴", "plant other palm tree"),
    HabitEmoji("🌵", "plant other cactus"),
    HabitEmoji("🌾", "plant other sheaf of rice"),
    HabitEmoji("🌿", "plant other herb"),
    HabitEmoji("☘️", "plant other shamrock"),
    HabitEmoji("🍀", "plant other four leaf clover"),
    HabitEmoji("🍁", "plant other maple leaf"),
    HabitEmoji("🍂", "plant other fallen leaf"),
    HabitEmoji("🍃", "plant other leaf fluttering in wind"),
    HabitEmoji("🪹", "plant other empty nest"),
    HabitEmoji("🪺", "plant other nest with eggs"),
    HabitEmoji("🍄", "plant other mushroom"),
    HabitEmoji("🪾", "plant other leafless tree"),
  ]),
  HabitEmojiCategory("Food", [
    HabitEmoji("🍇", "food fruit grapes"),
    HabitEmoji("🍈", "food fruit melon"),
    HabitEmoji("🍉", "food fruit watermelon"),
    HabitEmoji("🍊", "food fruit tangerine"),
    HabitEmoji("🍋", "food fruit lemon"),
    HabitEmoji("🍋‍🟩", "food fruit lime"),
    HabitEmoji("🍌", "food fruit banana"),
    HabitEmoji("🍍", "food fruit pineapple"),
    HabitEmoji("🥭", "food fruit mango"),
    HabitEmoji("🍎", "food fruit red apple"),
    HabitEmoji("🍏", "food fruit green apple"),
    HabitEmoji("🍐", "food fruit pear"),
    HabitEmoji("🍑", "food fruit peach"),
    HabitEmoji("🍒", "food fruit cherries"),
    HabitEmoji("🍓", "food fruit strawberry"),
    HabitEmoji("🫐", "food fruit blueberries"),
    HabitEmoji("🥝", "food fruit kiwi fruit"),
    HabitEmoji("🍅", "food fruit tomato"),
    HabitEmoji("🫒", "food fruit olive"),
    HabitEmoji("🥥", "food fruit coconut"),
    HabitEmoji("🥑", "food vegetable avocado"),
    HabitEmoji("🍆", "food vegetable eggplant"),
    HabitEmoji("🥔", "food vegetable potato"),
    HabitEmoji("🥕", "food vegetable carrot"),
    HabitEmoji("🌽", "food vegetable ear of corn"),
    HabitEmoji("🌶️", "food vegetable hot pepper"),
    HabitEmoji("🫑", "food vegetable bell pepper"),
    HabitEmoji("🥒", "food vegetable cucumber"),
    HabitEmoji("🥬", "food vegetable leafy green"),
    HabitEmoji("🥦", "food vegetable broccoli"),
    HabitEmoji("🧄", "food vegetable garlic"),
    HabitEmoji("🧅", "food vegetable onion"),
    HabitEmoji("🥜", "food vegetable peanuts"),
    HabitEmoji("🫘", "food vegetable beans"),
    HabitEmoji("🌰", "food vegetable chestnut"),
    HabitEmoji("🫚", "food vegetable ginger root"),
    HabitEmoji("🫛", "food vegetable pea pod"),
    HabitEmoji("🍄‍🟫", "food vegetable brown mushroom"),
    HabitEmoji("🫜", "food vegetable root vegetable"),
    HabitEmoji("🍞", "food prepared bread"),
    HabitEmoji("🥐", "food prepared croissant"),
    HabitEmoji("🥖", "food prepared baguette bread"),
    HabitEmoji("🫓", "food prepared flatbread"),
    HabitEmoji("🥨", "food prepared pretzel"),
    HabitEmoji("🥯", "food prepared bagel"),
    HabitEmoji("🥞", "food prepared pancakes"),
    HabitEmoji("🧇", "food prepared waffle"),
    HabitEmoji("🧀", "food prepared cheese wedge"),
    HabitEmoji("🍖", "food prepared meat on bone"),
    HabitEmoji("🍗", "food prepared poultry leg"),
    HabitEmoji("🥩", "food prepared cut of meat"),
    HabitEmoji("🥓", "food prepared bacon"),
    HabitEmoji("🍔", "food prepared hamburger"),
    HabitEmoji("🍟", "food prepared french fries"),
    HabitEmoji("🍕", "food prepared pizza"),
    HabitEmoji("🌭", "food prepared hot dog"),
    HabitEmoji("🥪", "food prepared sandwich"),
    HabitEmoji("🌮", "food prepared taco"),
    HabitEmoji("🌯", "food prepared burrito"),
    HabitEmoji("🫔", "food prepared tamale"),
    HabitEmoji("🥙", "food prepared stuffed flatbread"),
    HabitEmoji("🧆", "food prepared falafel"),
    HabitEmoji("🥚", "food prepared egg"),
    HabitEmoji("🍳", "food prepared cooking"),
    HabitEmoji("🥘", "food prepared shallow pan of food"),
    HabitEmoji("🍲", "food prepared pot of food"),
    HabitEmoji("🫕", "food prepared fondue"),
    HabitEmoji("🥣", "food prepared bowl with spoon"),
    HabitEmoji("🥗", "food prepared green salad"),
    HabitEmoji("🍿", "food prepared popcorn"),
    HabitEmoji("🧈", "food prepared butter"),
    HabitEmoji("🧂", "food prepared salt"),
    HabitEmoji("🥫", "food prepared canned food"),
    HabitEmoji("🍱", "food asian bento box"),
    HabitEmoji("🍘", "food asian rice cracker"),
    HabitEmoji("🍙", "food asian rice ball"),
    HabitEmoji("🍚", "food asian cooked rice"),
    HabitEmoji("🍛", "food asian curry rice"),
    HabitEmoji("🍜", "food asian steaming bowl"),
    HabitEmoji("🍝", "food asian spaghetti"),
    HabitEmoji("🍠", "food asian roasted sweet potato"),
    HabitEmoji("🍢", "food asian oden"),
    HabitEmoji("🍣", "food asian sushi"),
    HabitEmoji("🍤", "food asian fried shrimp"),
    HabitEmoji("🍥", "food asian fish cake with swirl"),
    HabitEmoji("🥮", "food asian moon cake"),
    HabitEmoji("🍡", "food asian dango"),
    HabitEmoji("🥟", "food asian dumpling"),
    HabitEmoji("🥠", "food asian fortune cookie"),
    HabitEmoji("🥡", "food asian takeout box"),
    HabitEmoji("🍦", "food sweet soft ice cream"),
    HabitEmoji("🍧", "food sweet shaved ice"),
    HabitEmoji("🍨", "food sweet ice cream"),
    HabitEmoji("🍩", "food sweet doughnut"),
    HabitEmoji("🍪", "food sweet cookie"),
    HabitEmoji("🎂", "food sweet birthday cake"),
    HabitEmoji("🍰", "food sweet shortcake"),
    HabitEmoji("🧁", "food sweet cupcake"),
    HabitEmoji("🥧", "food sweet pie"),
    HabitEmoji("🍫", "food sweet chocolate bar"),
    HabitEmoji("🍬", "food sweet candy"),
    HabitEmoji("🍭", "food sweet lollipop"),
    HabitEmoji("🍮", "food sweet custard"),
    HabitEmoji("🍯", "food sweet honey pot"),
    HabitEmoji("🍼", "drink baby bottle"),
    HabitEmoji("🥛", "drink glass of milk"),
    HabitEmoji("☕", "drink hot beverage"),
    HabitEmoji("🫖", "drink teapot"),
    HabitEmoji("🍵", "drink teacup without handle"),
    HabitEmoji("🍶", "drink sake"),
    HabitEmoji("🍾", "drink bottle with popping cork"),
    HabitEmoji("🍷", "drink wine glass"),
    HabitEmoji("🍸", "drink cocktail glass"),
    HabitEmoji("🍹", "drink tropical drink"),
    HabitEmoji("🍺", "drink beer mug"),
    HabitEmoji("🍻", "drink clinking beer mugs"),
    HabitEmoji("🥂", "drink clinking glasses"),
    HabitEmoji("🥃", "drink tumbler glass"),
    HabitEmoji("🫗", "drink pouring liquid"),
    HabitEmoji("🥤", "drink cup with straw"),
    HabitEmoji("🧋", "drink bubble tea"),
    HabitEmoji("🧃", "drink beverage box"),
    HabitEmoji("🧉", "drink mate"),
    HabitEmoji("🧊", "drink ice"),
    HabitEmoji("🥢", "dishware chopsticks"),
    HabitEmoji("🍽️", "dishware fork and knife with plate"),
    HabitEmoji("🍴", "dishware fork and knife"),
    HabitEmoji("🥄", "dishware spoon"),
    HabitEmoji("🔪", "dishware kitchen knife"),
    HabitEmoji("🫙", "dishware jar"),
    HabitEmoji("🏺", "dishware amphora"),
  ]),
  HabitEmojiCategory("Travel", [
    HabitEmoji("🌍", "place map globe showing Europe-Africa"),
    HabitEmoji("🌎", "place map globe showing Americas"),
    HabitEmoji("🌏", "place map globe showing Asia-Australia"),
    HabitEmoji("🌐", "place map globe with meridians"),
    HabitEmoji("🗺️", "place map world map"),
    HabitEmoji("🗾", "place map map of Japan"),
    HabitEmoji("🧭", "place map compass"),
    HabitEmoji("🏔️", "place geographic snow-capped mountain"),
    HabitEmoji("⛰️", "place geographic mountain"),
    HabitEmoji("🛘", "place geographic landslide"),
    HabitEmoji("🌋", "place geographic volcano"),
    HabitEmoji("🗻", "place geographic mount fuji"),
    HabitEmoji("🏕️", "place geographic camping"),
    HabitEmoji("🏖️", "place geographic beach with umbrella"),
    HabitEmoji("🏜️", "place geographic desert"),
    HabitEmoji("🏝️", "place geographic desert island"),
    HabitEmoji("🏞️", "place geographic national park"),
    HabitEmoji("🏟️", "place building stadium"),
    HabitEmoji("🏛️", "place building classical building"),
    HabitEmoji("🏗️", "place building building construction"),
    HabitEmoji("🧱", "place building brick"),
    HabitEmoji("🪨", "place building rock"),
    HabitEmoji("🪵", "place building wood"),
    HabitEmoji("🛖", "place building hut"),
    HabitEmoji("🏘️", "place building houses"),
    HabitEmoji("🏚️", "place building derelict house"),
    HabitEmoji("🏠", "place building house"),
    HabitEmoji("🏡", "place building house with garden"),
    HabitEmoji("🏢", "place building office building"),
    HabitEmoji("🏣", "place building Japanese post office"),
    HabitEmoji("🏤", "place building post office"),
    HabitEmoji("🏥", "place building hospital"),
    HabitEmoji("🏦", "place building bank"),
    HabitEmoji("🏨", "place building hotel"),
    HabitEmoji("🏩", "place building love hotel"),
    HabitEmoji("🏪", "place building convenience store"),
    HabitEmoji("🏫", "place building school"),
    HabitEmoji("🏬", "place building department store"),
    HabitEmoji("🏭", "place building factory"),
    HabitEmoji("🏯", "place building Japanese castle"),
    HabitEmoji("🏰", "place building castle"),
    HabitEmoji("💒", "place building wedding"),
    HabitEmoji("🗼", "place building Tokyo tower"),
    HabitEmoji("🗽", "place building Statue of Liberty"),
    HabitEmoji("⛪", "place religious church"),
    HabitEmoji("🕌", "place religious mosque"),
    HabitEmoji("🛕", "place religious hindu temple"),
    HabitEmoji("🕍", "place religious synagogue"),
    HabitEmoji("⛩️", "place religious shinto shrine"),
    HabitEmoji("🕋", "place religious kaaba"),
    HabitEmoji("⛲", "place other fountain"),
    HabitEmoji("⛺", "place other tent"),
    HabitEmoji("🌁", "place other foggy"),
    HabitEmoji("🌃", "place other night with stars"),
    HabitEmoji("🏙️", "place other cityscape"),
    HabitEmoji("🌄", "place other sunrise over mountains"),
    HabitEmoji("🌅", "place other sunrise"),
    HabitEmoji("🌆", "place other cityscape at dusk"),
    HabitEmoji("🌇", "place other sunset"),
    HabitEmoji("🌉", "place other bridge at night"),
    HabitEmoji("♨️", "place other hot springs"),
    HabitEmoji("🎠", "place other carousel horse"),
    HabitEmoji("🛝", "place other playground slide"),
    HabitEmoji("🎡", "place other ferris wheel"),
    HabitEmoji("🎢", "place other roller coaster"),
    HabitEmoji("💈", "place other barber pole"),
    HabitEmoji("🎪", "place other circus tent"),
    HabitEmoji("🚂", "transport ground locomotive"),
    HabitEmoji("🚃", "transport ground railway car"),
    HabitEmoji("🚄", "transport ground high-speed train"),
    HabitEmoji("🚅", "transport ground bullet train"),
    HabitEmoji("🚆", "transport ground train"),
    HabitEmoji("🚇", "transport ground metro"),
    HabitEmoji("🚈", "transport ground light rail"),
    HabitEmoji("🚉", "transport ground station"),
    HabitEmoji("🚊", "transport ground tram"),
    HabitEmoji("🚝", "transport ground monorail"),
    HabitEmoji("🚞", "transport ground mountain railway"),
    HabitEmoji("🚋", "transport ground tram car"),
    HabitEmoji("🚌", "transport ground bus"),
    HabitEmoji("🚍", "transport ground oncoming bus"),
    HabitEmoji("🚎", "transport ground trolleybus"),
    HabitEmoji("🚐", "transport ground minibus"),
    HabitEmoji("🚑", "transport ground ambulance"),
    HabitEmoji("🚒", "transport ground fire engine"),
    HabitEmoji("🚓", "transport ground police car"),
    HabitEmoji("🚔", "transport ground oncoming police car"),
    HabitEmoji("🚕", "transport ground taxi"),
    HabitEmoji("🚖", "transport ground oncoming taxi"),
    HabitEmoji("🚗", "transport ground automobile"),
    HabitEmoji("🚘", "transport ground oncoming automobile"),
    HabitEmoji("🚙", "transport ground sport utility vehicle"),
    HabitEmoji("🛻", "transport ground pickup truck"),
    HabitEmoji("🚚", "transport ground delivery truck"),
    HabitEmoji("🚛", "transport ground articulated lorry"),
    HabitEmoji("🚜", "transport ground tractor"),
    HabitEmoji("🏎️", "transport ground racing car"),
    HabitEmoji("🏍️", "transport ground motorcycle"),
    HabitEmoji("🛵", "transport ground motor scooter"),
    HabitEmoji("🦽", "transport ground manual wheelchair"),
    HabitEmoji("🦼", "transport ground motorized wheelchair"),
    HabitEmoji("🛺", "transport ground auto rickshaw"),
    HabitEmoji("🚲", "transport ground bicycle"),
    HabitEmoji("🛴", "transport ground kick scooter"),
    HabitEmoji("🛹", "transport ground skateboard"),
    HabitEmoji("🛼", "transport ground roller skate"),
    HabitEmoji("🚏", "transport ground bus stop"),
    HabitEmoji("🛣️", "transport ground motorway"),
    HabitEmoji("🛤️", "transport ground railway track"),
    HabitEmoji("🛢️", "transport ground oil drum"),
    HabitEmoji("⛽", "transport ground fuel pump"),
    HabitEmoji("🛞", "transport ground wheel"),
    HabitEmoji("🚨", "transport ground police car light"),
    HabitEmoji("🚥", "transport ground horizontal traffic light"),
    HabitEmoji("🚦", "transport ground vertical traffic light"),
    HabitEmoji("🛑", "transport ground stop sign"),
    HabitEmoji("🚧", "transport ground construction"),
    HabitEmoji("⚓", "transport water anchor"),
    HabitEmoji("🛟", "transport water ring buoy"),
    HabitEmoji("⛵", "transport water sailboat"),
    HabitEmoji("🛶", "transport water canoe"),
    HabitEmoji("🚤", "transport water speedboat"),
    HabitEmoji("🛳️", "transport water passenger ship"),
    HabitEmoji("⛴️", "transport water ferry"),
    HabitEmoji("🛥️", "transport water motor boat"),
    HabitEmoji("🚢", "transport water ship"),
    HabitEmoji("✈️", "transport air airplane"),
    HabitEmoji("🛩️", "transport air small airplane"),
    HabitEmoji("🛫", "transport air airplane departure"),
    HabitEmoji("🛬", "transport air airplane arrival"),
    HabitEmoji("🪂", "transport air parachute"),
    HabitEmoji("💺", "transport air seat"),
    HabitEmoji("🚁", "transport air helicopter"),
    HabitEmoji("🚟", "transport air suspension railway"),
    HabitEmoji("🚠", "transport air mountain cableway"),
    HabitEmoji("🚡", "transport air aerial tramway"),
    HabitEmoji("🛰️", "transport air satellite"),
    HabitEmoji("🚀", "transport air rocket"),
    HabitEmoji("🛸", "transport air flying saucer"),
    HabitEmoji("🛎️", "hotel bellhop bell"),
    HabitEmoji("🧳", "hotel luggage"),
    HabitEmoji("⌛", "time hourglass done"),
    HabitEmoji("⏳", "time hourglass not done"),
    HabitEmoji("⌚", "time watch"),
    HabitEmoji("⏰", "time alarm clock"),
    HabitEmoji("⏱️", "time stopwatch"),
    HabitEmoji("⏲️", "time timer clock"),
    HabitEmoji("🕰️", "time mantelpiece clock"),
    HabitEmoji("🕛", "time twelve o’clock"),
    HabitEmoji("🕧", "time twelve-thirty"),
    HabitEmoji("🕐", "time one o’clock"),
    HabitEmoji("🕜", "time one-thirty"),
    HabitEmoji("🕑", "time two o’clock"),
    HabitEmoji("🕝", "time two-thirty"),
    HabitEmoji("🕒", "time three o’clock"),
    HabitEmoji("🕞", "time three-thirty"),
    HabitEmoji("🕓", "time four o’clock"),
    HabitEmoji("🕟", "time four-thirty"),
    HabitEmoji("🕔", "time five o’clock"),
    HabitEmoji("🕠", "time five-thirty"),
    HabitEmoji("🕕", "time six o’clock"),
    HabitEmoji("🕡", "time six-thirty"),
    HabitEmoji("🕖", "time seven o’clock"),
    HabitEmoji("🕢", "time seven-thirty"),
    HabitEmoji("🕗", "time eight o’clock"),
    HabitEmoji("🕣", "time eight-thirty"),
    HabitEmoji("🕘", "time nine o’clock"),
    HabitEmoji("🕤", "time nine-thirty"),
    HabitEmoji("🕙", "time ten o’clock"),
    HabitEmoji("🕥", "time ten-thirty"),
    HabitEmoji("🕚", "time eleven o’clock"),
    HabitEmoji("🕦", "time eleven-thirty"),
    HabitEmoji("🌑", "sky & weather new moon"),
    HabitEmoji("🌒", "sky & weather waxing crescent moon"),
    HabitEmoji("🌓", "sky & weather first quarter moon"),
    HabitEmoji("🌔", "sky & weather waxing gibbous moon"),
    HabitEmoji("🌕", "sky & weather full moon"),
    HabitEmoji("🌖", "sky & weather waning gibbous moon"),
    HabitEmoji("🌗", "sky & weather last quarter moon"),
    HabitEmoji("🌘", "sky & weather waning crescent moon"),
    HabitEmoji("🌙", "sky & weather crescent moon"),
    HabitEmoji("🌚", "sky & weather new moon face"),
    HabitEmoji("🌛", "sky & weather first quarter moon face"),
    HabitEmoji("🌜", "sky & weather last quarter moon face"),
    HabitEmoji("🌡️", "sky & weather thermometer"),
    HabitEmoji("☀️", "sky & weather sun"),
    HabitEmoji("🌝", "sky & weather full moon face"),
    HabitEmoji("🌞", "sky & weather sun with face"),
    HabitEmoji("🪐", "sky & weather ringed planet"),
    HabitEmoji("⭐", "sky & weather star"),
    HabitEmoji("🌟", "sky & weather glowing star"),
    HabitEmoji("🌠", "sky & weather shooting star"),
    HabitEmoji("🌌", "sky & weather milky way"),
    HabitEmoji("☁️", "sky & weather cloud"),
    HabitEmoji("⛅", "sky & weather sun behind cloud"),
    HabitEmoji("⛈️", "sky & weather cloud with lightning and rain"),
    HabitEmoji("🌤️", "sky & weather sun behind small cloud"),
    HabitEmoji("🌥️", "sky & weather sun behind large cloud"),
    HabitEmoji("🌦️", "sky & weather sun behind rain cloud"),
    HabitEmoji("🌧️", "sky & weather cloud with rain"),
    HabitEmoji("🌨️", "sky & weather cloud with snow"),
    HabitEmoji("🌩️", "sky & weather cloud with lightning"),
    HabitEmoji("🌪️", "sky & weather tornado"),
    HabitEmoji("🌫️", "sky & weather fog"),
    HabitEmoji("🌬️", "sky & weather wind face"),
    HabitEmoji("🌀", "sky & weather cyclone"),
    HabitEmoji("🌈", "sky & weather rainbow"),
    HabitEmoji("🌂", "sky & weather closed umbrella"),
    HabitEmoji("☂️", "sky & weather umbrella"),
    HabitEmoji("☔", "sky & weather umbrella with rain drops"),
    HabitEmoji("⛱️", "sky & weather umbrella on ground"),
    HabitEmoji("⚡", "sky & weather high voltage"),
    HabitEmoji("❄️", "sky & weather snowflake"),
    HabitEmoji("☃️", "sky & weather snowman"),
    HabitEmoji("⛄", "sky & weather snowman without snow"),
    HabitEmoji("☄️", "sky & weather comet"),
    HabitEmoji("🔥", "sky & weather fire"),
    HabitEmoji("💧", "sky & weather droplet"),
    HabitEmoji("🌊", "sky & weather water wave"),
  ]),
  HabitEmojiCategory("Activities", [
    HabitEmoji("🎃", "event jack-o-lantern"),
    HabitEmoji("🎄", "event Christmas tree"),
    HabitEmoji("🎆", "event fireworks"),
    HabitEmoji("🎇", "event sparkler"),
    HabitEmoji("🧨", "event firecracker"),
    HabitEmoji("✨", "event sparkles"),
    HabitEmoji("🎈", "event balloon"),
    HabitEmoji("🎉", "event party popper"),
    HabitEmoji("🎊", "event confetti ball"),
    HabitEmoji("🎋", "event tanabata tree"),
    HabitEmoji("🎍", "event pine decoration"),
    HabitEmoji("🎎", "event Japanese dolls"),
    HabitEmoji("🎏", "event carp streamer"),
    HabitEmoji("🎐", "event wind chime"),
    HabitEmoji("🎑", "event moon viewing ceremony"),
    HabitEmoji("🧧", "event red envelope"),
    HabitEmoji("🎀", "event ribbon"),
    HabitEmoji("🎁", "event wrapped gift"),
    HabitEmoji("🎗️", "event reminder ribbon"),
    HabitEmoji("🎟️", "event admission tickets"),
    HabitEmoji("🎫", "event ticket"),
    HabitEmoji("🎖️", "award medal military medal"),
    HabitEmoji("🏆", "award medal trophy"),
    HabitEmoji("🏅", "award medal sports medal"),
    HabitEmoji("🥇", "award medal 1st place medal"),
    HabitEmoji("🥈", "award medal 2nd place medal"),
    HabitEmoji("🥉", "award medal 3rd place medal"),
    HabitEmoji("⚽", "sport soccer ball"),
    HabitEmoji("⚾", "sport baseball"),
    HabitEmoji("🥎", "sport softball"),
    HabitEmoji("🏀", "sport basketball"),
    HabitEmoji("🏐", "sport volleyball"),
    HabitEmoji("🏈", "sport american football"),
    HabitEmoji("🏉", "sport rugby football"),
    HabitEmoji("🎾", "sport tennis"),
    HabitEmoji("🥏", "sport flying disc"),
    HabitEmoji("🎳", "sport bowling"),
    HabitEmoji("🏏", "sport cricket game"),
    HabitEmoji("🏑", "sport field hockey"),
    HabitEmoji("🏒", "sport ice hockey"),
    HabitEmoji("🥍", "sport lacrosse"),
    HabitEmoji("🏓", "sport ping pong"),
    HabitEmoji("🏸", "sport badminton"),
    HabitEmoji("🥊", "sport boxing glove"),
    HabitEmoji("🥋", "sport martial arts uniform"),
    HabitEmoji("🥅", "sport goal net"),
    HabitEmoji("⛳", "sport flag in hole"),
    HabitEmoji("⛸️", "sport ice skate"),
    HabitEmoji("🎣", "sport fishing pole"),
    HabitEmoji("🤿", "sport diving mask"),
    HabitEmoji("🎽", "sport running shirt"),
    HabitEmoji("🎿", "sport skis"),
    HabitEmoji("🛷", "sport sled"),
    HabitEmoji("🥌", "sport curling stone"),
    HabitEmoji("🎯", "game bullseye"),
    HabitEmoji("🪀", "game yo-yo"),
    HabitEmoji("🪁", "game kite"),
    HabitEmoji("🔫", "game water pistol"),
    HabitEmoji("🎱", "game pool 8 ball"),
    HabitEmoji("🔮", "game crystal ball"),
    HabitEmoji("🪄", "game magic wand"),
    HabitEmoji("🎮", "game video game"),
    HabitEmoji("🕹️", "game joystick"),
    HabitEmoji("🎰", "game slot machine"),
    HabitEmoji("🎲", "game game die"),
    HabitEmoji("🧩", "game puzzle piece"),
    HabitEmoji("🧸", "game teddy bear"),
    HabitEmoji("🪅", "game piñata"),
    HabitEmoji("🪩", "game mirror ball"),
    HabitEmoji("🪆", "game nesting dolls"),
    HabitEmoji("♠️", "game spade suit"),
    HabitEmoji("♥️", "game heart suit"),
    HabitEmoji("♦️", "game diamond suit"),
    HabitEmoji("♣️", "game club suit"),
    HabitEmoji("♟️", "game chess pawn"),
    HabitEmoji("🃏", "game joker"),
    HabitEmoji("🀄", "game mahjong red dragon"),
    HabitEmoji("🎴", "game flower playing cards"),
    HabitEmoji("🎭", "arts & crafts performing arts"),
    HabitEmoji("🖼️", "arts & crafts framed picture"),
    HabitEmoji("🎨", "arts & crafts artist palette"),
    HabitEmoji("🧵", "arts & crafts thread"),
    HabitEmoji("🪡", "arts & crafts sewing needle"),
    HabitEmoji("🧶", "arts & crafts yarn"),
    HabitEmoji("🪢", "arts & crafts knot"),
  ]),
  HabitEmojiCategory("Objects", [
    HabitEmoji("👓", "clothing glasses"),
    HabitEmoji("🕶️", "clothing sunglasses"),
    HabitEmoji("🥽", "clothing goggles"),
    HabitEmoji("🥼", "clothing lab coat"),
    HabitEmoji("🦺", "clothing safety vest"),
    HabitEmoji("👔", "clothing necktie"),
    HabitEmoji("👕", "clothing t-shirt"),
    HabitEmoji("👖", "clothing jeans"),
    HabitEmoji("🧣", "clothing scarf"),
    HabitEmoji("🧤", "clothing gloves"),
    HabitEmoji("🧥", "clothing coat"),
    HabitEmoji("🧦", "clothing socks"),
    HabitEmoji("👗", "clothing dress"),
    HabitEmoji("👘", "clothing kimono"),
    HabitEmoji("🥻", "clothing sari"),
    HabitEmoji("🩱", "clothing one-piece swimsuit"),
    HabitEmoji("🩲", "clothing briefs"),
    HabitEmoji("🩳", "clothing shorts"),
    HabitEmoji("👙", "clothing bikini"),
    HabitEmoji("👚", "clothing woman’s clothes"),
    HabitEmoji("🪭", "clothing folding hand fan"),
    HabitEmoji("👛", "clothing purse"),
    HabitEmoji("👜", "clothing handbag"),
    HabitEmoji("👝", "clothing clutch bag"),
    HabitEmoji("🛍️", "clothing shopping bags"),
    HabitEmoji("🎒", "clothing backpack"),
    HabitEmoji("🩴", "clothing thong sandal"),
    HabitEmoji("👞", "clothing man’s shoe"),
    HabitEmoji("👟", "clothing running shoe"),
    HabitEmoji("🥾", "clothing hiking boot"),
    HabitEmoji("🥿", "clothing flat shoe"),
    HabitEmoji("👠", "clothing high-heeled shoe"),
    HabitEmoji("👡", "clothing woman’s sandal"),
    HabitEmoji("🩰", "clothing ballet shoes"),
    HabitEmoji("👢", "clothing woman’s boot"),
    HabitEmoji("🪮", "clothing hair pick"),
    HabitEmoji("👑", "clothing crown"),
    HabitEmoji("👒", "clothing woman’s hat"),
    HabitEmoji("🎩", "clothing top hat"),
    HabitEmoji("🎓", "clothing graduation cap"),
    HabitEmoji("🧢", "clothing billed cap"),
    HabitEmoji("🪖", "clothing military helmet"),
    HabitEmoji("⛑️", "clothing rescue worker’s helmet"),
    HabitEmoji("📿", "clothing prayer beads"),
    HabitEmoji("💄", "clothing lipstick"),
    HabitEmoji("💍", "clothing ring"),
    HabitEmoji("💎", "clothing gem stone"),
    HabitEmoji("🔇", "sound muted speaker"),
    HabitEmoji("🔈", "sound speaker low volume"),
    HabitEmoji("🔉", "sound speaker medium volume"),
    HabitEmoji("🔊", "sound speaker high volume"),
    HabitEmoji("📢", "sound loudspeaker"),
    HabitEmoji("📣", "sound megaphone"),
    HabitEmoji("📯", "sound postal horn"),
    HabitEmoji("🔔", "sound bell"),
    HabitEmoji("🔕", "sound bell with slash"),
    HabitEmoji("🎼", "music musical score"),
    HabitEmoji("🎵", "music musical note"),
    HabitEmoji("🎶", "music musical notes"),
    HabitEmoji("🎙️", "music studio microphone"),
    HabitEmoji("🎚️", "music level slider"),
    HabitEmoji("🎛️", "music control knobs"),
    HabitEmoji("🎤", "music microphone"),
    HabitEmoji("🎧", "music headphone"),
    HabitEmoji("📻", "music radio"),
    HabitEmoji("🎷", "musical instrument saxophone"),
    HabitEmoji("🎺", "musical instrument trumpet"),
    HabitEmoji("🪊", "musical instrument trombone"),
    HabitEmoji("🪗", "musical instrument accordion"),
    HabitEmoji("🎸", "musical instrument guitar"),
    HabitEmoji("🎹", "musical instrument musical keyboard"),
    HabitEmoji("🎻", "musical instrument violin"),
    HabitEmoji("🪕", "musical instrument banjo"),
    HabitEmoji("🥁", "musical instrument drum"),
    HabitEmoji("🪘", "musical instrument long drum"),
    HabitEmoji("🪇", "musical instrument maracas"),
    HabitEmoji("🪈", "musical instrument flute"),
    HabitEmoji("🪉", "musical instrument harp"),
    HabitEmoji("📱", "phone mobile phone"),
    HabitEmoji("📲", "phone mobile phone with arrow"),
    HabitEmoji("☎️", "phone telephone"),
    HabitEmoji("📞", "phone telephone receiver"),
    HabitEmoji("📟", "phone pager"),
    HabitEmoji("📠", "phone fax machine"),
    HabitEmoji("🔋", "computer battery"),
    HabitEmoji("🪫", "computer low battery"),
    HabitEmoji("🔌", "computer electric plug"),
    HabitEmoji("💻", "computer laptop"),
    HabitEmoji("🖥️", "computer desktop computer"),
    HabitEmoji("🖨️", "computer printer"),
    HabitEmoji("⌨️", "computer keyboard"),
    HabitEmoji("🖱️", "computer computer mouse"),
    HabitEmoji("🖲️", "computer trackball"),
    HabitEmoji("💽", "computer computer disk"),
    HabitEmoji("💾", "computer floppy disk"),
    HabitEmoji("💿", "computer optical disk"),
    HabitEmoji("📀", "computer dvd"),
    HabitEmoji("🧮", "computer abacus"),
    HabitEmoji("🎥", "light & video movie camera"),
    HabitEmoji("🎞️", "light & video film frames"),
    HabitEmoji("📽️", "light & video film projector"),
    HabitEmoji("🎬", "light & video clapper board"),
    HabitEmoji("📺", "light & video television"),
    HabitEmoji("📷", "light & video camera"),
    HabitEmoji("📸", "light & video camera with flash"),
    HabitEmoji("📹", "light & video video camera"),
    HabitEmoji("📼", "light & video videocassette"),
    HabitEmoji("🔍", "light & video magnifying glass tilted left"),
    HabitEmoji("🔎", "light & video magnifying glass tilted right"),
    HabitEmoji("🕯️", "light & video candle"),
    HabitEmoji("💡", "light & video light bulb"),
    HabitEmoji("🔦", "light & video flashlight"),
    HabitEmoji("🏮", "light & video red paper lantern"),
    HabitEmoji("🪔", "light & video diya lamp"),
    HabitEmoji("📔", "book paper notebook with decorative cover"),
    HabitEmoji("📕", "book paper closed book"),
    HabitEmoji("📖", "book paper open book"),
    HabitEmoji("📗", "book paper green book"),
    HabitEmoji("📘", "book paper blue book"),
    HabitEmoji("📙", "book paper orange book"),
    HabitEmoji("📚", "book paper books"),
    HabitEmoji("📓", "book paper notebook"),
    HabitEmoji("📒", "book paper ledger"),
    HabitEmoji("📃", "book paper page with curl"),
    HabitEmoji("📜", "book paper scroll"),
    HabitEmoji("📄", "book paper page facing up"),
    HabitEmoji("📰", "book paper newspaper"),
    HabitEmoji("🗞️", "book paper rolled-up newspaper"),
    HabitEmoji("📑", "book paper bookmark tabs"),
    HabitEmoji("🔖", "book paper bookmark"),
    HabitEmoji("🏷️", "book paper label"),
    HabitEmoji("🪙", "money coin"),
    HabitEmoji("💰", "money money bag"),
    HabitEmoji("🪎", "money treasure chest"),
    HabitEmoji("💴", "money yen banknote"),
    HabitEmoji("💵", "money dollar banknote"),
    HabitEmoji("💶", "money euro banknote"),
    HabitEmoji("💷", "money pound banknote"),
    HabitEmoji("💸", "money money with wings"),
    HabitEmoji("💳", "money credit card"),
    HabitEmoji("🧾", "money receipt"),
    HabitEmoji("💹", "money chart increasing with yen"),
    HabitEmoji("✉️", "mail envelope"),
    HabitEmoji("📧", "mail e-mail"),
    HabitEmoji("📨", "mail incoming envelope"),
    HabitEmoji("📩", "mail envelope with arrow"),
    HabitEmoji("📤", "mail outbox tray"),
    HabitEmoji("📥", "mail inbox tray"),
    HabitEmoji("📦", "mail package"),
    HabitEmoji("📫", "mail closed mailbox with raised flag"),
    HabitEmoji("📪", "mail closed mailbox with lowered flag"),
    HabitEmoji("📬", "mail open mailbox with raised flag"),
    HabitEmoji("📭", "mail open mailbox with lowered flag"),
    HabitEmoji("📮", "mail postbox"),
    HabitEmoji("🗳️", "mail ballot box with ballot"),
    HabitEmoji("✏️", "writing pencil"),
    HabitEmoji("✒️", "writing black nib"),
    HabitEmoji("🖋️", "writing fountain pen"),
    HabitEmoji("🖊️", "writing pen"),
    HabitEmoji("🖌️", "writing paintbrush"),
    HabitEmoji("🖍️", "writing crayon"),
    HabitEmoji("📝", "writing memo"),
    HabitEmoji("💼", "office briefcase"),
    HabitEmoji("📁", "office file folder"),
    HabitEmoji("📂", "office open file folder"),
    HabitEmoji("🗂️", "office card index dividers"),
    HabitEmoji("📅", "office calendar"),
    HabitEmoji("📆", "office tear-off calendar"),
    HabitEmoji("🗒️", "office spiral notepad"),
    HabitEmoji("🗓️", "office spiral calendar"),
    HabitEmoji("📇", "office card index"),
    HabitEmoji("📈", "office chart increasing"),
    HabitEmoji("📉", "office chart decreasing"),
    HabitEmoji("📊", "office bar chart"),
    HabitEmoji("📋", "office clipboard"),
    HabitEmoji("📌", "office pushpin"),
    HabitEmoji("📍", "office round pushpin"),
    HabitEmoji("📎", "office paperclip"),
    HabitEmoji("🖇️", "office linked paperclips"),
    HabitEmoji("📏", "office straight ruler"),
    HabitEmoji("📐", "office triangular ruler"),
    HabitEmoji("✂️", "office scissors"),
    HabitEmoji("🗃️", "office card file box"),
    HabitEmoji("🗄️", "office file cabinet"),
    HabitEmoji("🗑️", "office wastebasket"),
    HabitEmoji("🔒", "lock locked"),
    HabitEmoji("🔓", "lock unlocked"),
    HabitEmoji("🔏", "lock locked with pen"),
    HabitEmoji("🔐", "lock locked with key"),
    HabitEmoji("🔑", "lock key"),
    HabitEmoji("🗝️", "lock old key"),
    HabitEmoji("🔨", "tool hammer"),
    HabitEmoji("🪓", "tool axe"),
    HabitEmoji("⛏️", "tool pick"),
    HabitEmoji("⚒️", "tool hammer and pick"),
    HabitEmoji("🛠️", "tool hammer and wrench"),
    HabitEmoji("🗡️", "tool dagger"),
    HabitEmoji("⚔️", "tool crossed swords"),
    HabitEmoji("💣", "tool bomb"),
    HabitEmoji("🪃", "tool boomerang"),
    HabitEmoji("🏹", "tool bow and arrow"),
    HabitEmoji("🛡️", "tool shield"),
    HabitEmoji("🪚", "tool carpentry saw"),
    HabitEmoji("🔧", "tool wrench"),
    HabitEmoji("🪛", "tool screwdriver"),
    HabitEmoji("🔩", "tool nut and bolt"),
    HabitEmoji("⚙️", "tool gear"),
    HabitEmoji("🗜️", "tool clamp"),
    HabitEmoji("⚖️", "tool balance scale"),
    HabitEmoji("🦯", "tool white cane"),
    HabitEmoji("🔗", "tool link"),
    HabitEmoji("⛓️‍💥", "tool broken chain"),
    HabitEmoji("⛓️", "tool chains"),
    HabitEmoji("🪝", "tool hook"),
    HabitEmoji("🧰", "tool toolbox"),
    HabitEmoji("🧲", "tool magnet"),
    HabitEmoji("🪜", "tool ladder"),
    HabitEmoji("🪏", "tool shovel"),
    HabitEmoji("⚗️", "science alembic"),
    HabitEmoji("🧪", "science test tube"),
    HabitEmoji("🧫", "science petri dish"),
    HabitEmoji("🧬", "science dna"),
    HabitEmoji("🔬", "science microscope"),
    HabitEmoji("🔭", "science telescope"),
    HabitEmoji("📡", "science satellite antenna"),
    HabitEmoji("💉", "medical syringe"),
    HabitEmoji("🩸", "medical drop of blood"),
    HabitEmoji("💊", "medical pill"),
    HabitEmoji("🩹", "medical adhesive bandage"),
    HabitEmoji("🩼", "medical crutch"),
    HabitEmoji("🩺", "medical stethoscope"),
    HabitEmoji("🩻", "medical x-ray"),
    HabitEmoji("🚪", "household door"),
    HabitEmoji("🛗", "household elevator"),
    HabitEmoji("🪞", "household mirror"),
    HabitEmoji("🪟", "household window"),
    HabitEmoji("🛏️", "household bed"),
    HabitEmoji("🛋️", "household couch and lamp"),
    HabitEmoji("🪑", "household chair"),
    HabitEmoji("🚽", "household toilet"),
    HabitEmoji("🪠", "household plunger"),
    HabitEmoji("🚿", "household shower"),
    HabitEmoji("🛁", "household bathtub"),
    HabitEmoji("🪤", "household mouse trap"),
    HabitEmoji("🪒", "household razor"),
    HabitEmoji("🧴", "household lotion bottle"),
    HabitEmoji("🧷", "household safety pin"),
    HabitEmoji("🧹", "household broom"),
    HabitEmoji("🧺", "household basket"),
    HabitEmoji("🧻", "household roll of paper"),
    HabitEmoji("🪣", "household bucket"),
    HabitEmoji("🧼", "household soap"),
    HabitEmoji("🫧", "household bubbles"),
    HabitEmoji("🪥", "household toothbrush"),
    HabitEmoji("🧽", "household sponge"),
    HabitEmoji("🧯", "household fire extinguisher"),
    HabitEmoji("🛒", "household shopping cart"),
    HabitEmoji("🚬", "other object cigarette"),
    HabitEmoji("⚰️", "other object coffin"),
    HabitEmoji("🪦", "other object headstone"),
    HabitEmoji("⚱️", "other object funeral urn"),
    HabitEmoji("🧿", "other object nazar amulet"),
    HabitEmoji("🪬", "other object hamsa"),
    HabitEmoji("🗿", "other object moai"),
    HabitEmoji("🪧", "other object placard"),
    HabitEmoji("🪪", "other object identification card"),
  ]),
  HabitEmojiCategory("Symbols", [
    HabitEmoji("🏧", "transport sign ATM sign"),
    HabitEmoji("🚮", "transport sign litter in bin sign"),
    HabitEmoji("🚰", "transport sign potable water"),
    HabitEmoji("♿", "transport sign wheelchair symbol"),
    HabitEmoji("🚹", "transport sign men’s room"),
    HabitEmoji("🚺", "transport sign women’s room"),
    HabitEmoji("🚻", "transport sign restroom"),
    HabitEmoji("🚼", "transport sign baby symbol"),
    HabitEmoji("🚾", "transport sign water closet"),
    HabitEmoji("🛂", "transport sign passport control"),
    HabitEmoji("🛃", "transport sign customs"),
    HabitEmoji("🛄", "transport sign baggage claim"),
    HabitEmoji("🛅", "transport sign left luggage"),
    HabitEmoji("⚠️", "warning warning"),
    HabitEmoji("🚸", "warning children crossing"),
    HabitEmoji("⛔", "warning no entry"),
    HabitEmoji("🚫", "warning prohibited"),
    HabitEmoji("🚳", "warning no bicycles"),
    HabitEmoji("🚭", "warning no smoking"),
    HabitEmoji("🚯", "warning no littering"),
    HabitEmoji("🚱", "warning non-potable water"),
    HabitEmoji("🚷", "warning no pedestrians"),
    HabitEmoji("📵", "warning no mobile phones"),
    HabitEmoji("🔞", "warning no one under eighteen"),
    HabitEmoji("☢️", "warning radioactive"),
    HabitEmoji("☣️", "warning biohazard"),
    HabitEmoji("⬆️", "arrow up arrow"),
    HabitEmoji("↗️", "arrow up-right arrow"),
    HabitEmoji("➡️", "arrow right arrow"),
    HabitEmoji("↘️", "arrow down-right arrow"),
    HabitEmoji("⬇️", "arrow down arrow"),
    HabitEmoji("↙️", "arrow down-left arrow"),
    HabitEmoji("⬅️", "arrow left arrow"),
    HabitEmoji("↖️", "arrow up-left arrow"),
    HabitEmoji("↕️", "arrow up-down arrow"),
    HabitEmoji("↔️", "arrow left-right arrow"),
    HabitEmoji("↩️", "arrow right arrow curving left"),
    HabitEmoji("↪️", "arrow left arrow curving right"),
    HabitEmoji("⤴️", "arrow right arrow curving up"),
    HabitEmoji("⤵️", "arrow right arrow curving down"),
    HabitEmoji("🔃", "arrow clockwise vertical arrows"),
    HabitEmoji("🔄", "arrow counterclockwise arrows button"),
    HabitEmoji("🔙", "arrow BACK arrow"),
    HabitEmoji("🔚", "arrow END arrow"),
    HabitEmoji("🔛", "arrow ON! arrow"),
    HabitEmoji("🔜", "arrow SOON arrow"),
    HabitEmoji("🔝", "arrow TOP arrow"),
    HabitEmoji("🛐", "religion place of worship"),
    HabitEmoji("⚛️", "religion atom symbol"),
    HabitEmoji("🕉️", "religion om"),
    HabitEmoji("✡️", "religion star of David"),
    HabitEmoji("☸️", "religion wheel of dharma"),
    HabitEmoji("☯️", "religion yin yang"),
    HabitEmoji("✝️", "religion latin cross"),
    HabitEmoji("☦️", "religion orthodox cross"),
    HabitEmoji("☪️", "religion star and crescent"),
    HabitEmoji("☮️", "religion peace symbol"),
    HabitEmoji("🕎", "religion menorah"),
    HabitEmoji("🔯", "religion dotted six-pointed star"),
    HabitEmoji("🪯", "religion khanda"),
    HabitEmoji("♈", "zodiac Aries"),
    HabitEmoji("♉", "zodiac Taurus"),
    HabitEmoji("♊", "zodiac Gemini"),
    HabitEmoji("♋", "zodiac Cancer"),
    HabitEmoji("♌", "zodiac Leo"),
    HabitEmoji("♍", "zodiac Virgo"),
    HabitEmoji("♎", "zodiac Libra"),
    HabitEmoji("♏", "zodiac Scorpio"),
    HabitEmoji("♐", "zodiac Sagittarius"),
    HabitEmoji("♑", "zodiac Capricorn"),
    HabitEmoji("♒", "zodiac Aquarius"),
    HabitEmoji("♓", "zodiac Pisces"),
    HabitEmoji("⛎", "zodiac Ophiuchus"),
    HabitEmoji("🔀", "av symbol shuffle tracks button"),
    HabitEmoji("🔁", "av symbol repeat button"),
    HabitEmoji("🔂", "av symbol repeat single button"),
    HabitEmoji("▶️", "av symbol play button"),
    HabitEmoji("⏩", "av symbol fast-forward button"),
    HabitEmoji("⏭️", "av symbol next track button"),
    HabitEmoji("⏯️", "av symbol play or pause button"),
    HabitEmoji("◀️", "av symbol reverse button"),
    HabitEmoji("⏪", "av symbol fast reverse button"),
    HabitEmoji("⏮️", "av symbol last track button"),
    HabitEmoji("🔼", "av symbol upwards button"),
    HabitEmoji("⏫", "av symbol fast up button"),
    HabitEmoji("🔽", "av symbol downwards button"),
    HabitEmoji("⏬", "av symbol fast down button"),
    HabitEmoji("⏸️", "av symbol pause button"),
    HabitEmoji("⏹️", "av symbol stop button"),
    HabitEmoji("⏺️", "av symbol record button"),
    HabitEmoji("⏏️", "av symbol eject button"),
    HabitEmoji("🎦", "av symbol cinema"),
    HabitEmoji("🔅", "av symbol dim button"),
    HabitEmoji("🔆", "av symbol bright button"),
    HabitEmoji("📶", "av symbol antenna bars"),
    HabitEmoji("🛜", "av symbol wireless"),
    HabitEmoji("📳", "av symbol vibration mode"),
    HabitEmoji("📴", "av symbol mobile phone off"),
    HabitEmoji("♀️", "gender female sign"),
    HabitEmoji("♂️", "gender male sign"),
    HabitEmoji("⚧️", "gender transgender symbol"),
    HabitEmoji("✖️", "math multiply"),
    HabitEmoji("➕", "math plus"),
    HabitEmoji("➖", "math minus"),
    HabitEmoji("➗", "math divide"),
    HabitEmoji("🟰", "math heavy equals sign"),
    HabitEmoji("♾️", "math infinity"),
    HabitEmoji("‼️", "punctuation double exclamation mark"),
    HabitEmoji("⁉️", "punctuation exclamation question mark"),
    HabitEmoji("❓", "punctuation red question mark"),
    HabitEmoji("❔", "punctuation white question mark"),
    HabitEmoji("❕", "punctuation white exclamation mark"),
    HabitEmoji("❗", "punctuation red exclamation mark"),
    HabitEmoji("〰️", "punctuation wavy dash"),
    HabitEmoji("💱", "currency currency exchange"),
    HabitEmoji("💲", "currency heavy dollar sign"),
    HabitEmoji("⚕️", "other symbol medical symbol"),
    HabitEmoji("♻️", "other symbol recycling symbol"),
    HabitEmoji("⚜️", "other symbol fleur-de-lis"),
    HabitEmoji("🔱", "other symbol trident emblem"),
    HabitEmoji("📛", "other symbol name badge"),
    HabitEmoji("🔰", "other symbol Japanese symbol for beginner"),
    HabitEmoji("⭕", "other symbol hollow red circle"),
    HabitEmoji("✅", "other symbol check mark button"),
    HabitEmoji("☑️", "other symbol check box with check"),
    HabitEmoji("✔️", "other symbol check mark"),
    HabitEmoji("❌", "other symbol cross mark"),
    HabitEmoji("❎", "other symbol cross mark button"),
    HabitEmoji("➰", "other symbol curly loop"),
    HabitEmoji("➿", "other symbol double curly loop"),
    HabitEmoji("〽️", "other symbol part alternation mark"),
    HabitEmoji("✳️", "other symbol eight-spoked asterisk"),
    HabitEmoji("✴️", "other symbol eight-pointed star"),
    HabitEmoji("❇️", "other symbol sparkle"),
    HabitEmoji("©️", "other symbol copyright"),
    HabitEmoji("®️", "other symbol registered"),
    HabitEmoji("™️", "other symbol trade mark"),
    HabitEmoji("🫟", "other symbol splatter"),
    HabitEmoji("#️⃣", "keycap keycap: #"),
    HabitEmoji("*️⃣", "keycap keycap: *"),
    HabitEmoji("0️⃣", "keycap keycap: 0"),
    HabitEmoji("1️⃣", "keycap keycap: 1"),
    HabitEmoji("2️⃣", "keycap keycap: 2"),
    HabitEmoji("3️⃣", "keycap keycap: 3"),
    HabitEmoji("4️⃣", "keycap keycap: 4"),
    HabitEmoji("5️⃣", "keycap keycap: 5"),
    HabitEmoji("6️⃣", "keycap keycap: 6"),
    HabitEmoji("7️⃣", "keycap keycap: 7"),
    HabitEmoji("8️⃣", "keycap keycap: 8"),
    HabitEmoji("9️⃣", "keycap keycap: 9"),
    HabitEmoji("🔟", "keycap keycap: 10"),
    HabitEmoji("🔠", "alphanum input latin uppercase"),
    HabitEmoji("🔡", "alphanum input latin lowercase"),
    HabitEmoji("🔢", "alphanum input numbers"),
    HabitEmoji("🔣", "alphanum input symbols"),
    HabitEmoji("🔤", "alphanum input latin letters"),
    HabitEmoji("🅰️", "alphanum A button (blood type)"),
    HabitEmoji("🆎", "alphanum AB button (blood type)"),
    HabitEmoji("🅱️", "alphanum B button (blood type)"),
    HabitEmoji("🆑", "alphanum CL button"),
    HabitEmoji("🆒", "alphanum COOL button"),
    HabitEmoji("🆓", "alphanum FREE button"),
    HabitEmoji("ℹ️", "alphanum information"),
    HabitEmoji("🆔", "alphanum ID button"),
    HabitEmoji("Ⓜ️", "alphanum circled M"),
    HabitEmoji("🆕", "alphanum NEW button"),
    HabitEmoji("🆖", "alphanum NG button"),
    HabitEmoji("🅾️", "alphanum O button (blood type)"),
    HabitEmoji("🆗", "alphanum OK button"),
    HabitEmoji("🅿️", "alphanum P button"),
    HabitEmoji("🆘", "alphanum SOS button"),
    HabitEmoji("🆙", "alphanum UP! button"),
    HabitEmoji("🆚", "alphanum VS button"),
    HabitEmoji("🈁", "alphanum Japanese “here” button"),
    HabitEmoji("🈂️", "alphanum Japanese “service charge” button"),
    HabitEmoji("🈷️", "alphanum Japanese “monthly amount” button"),
    HabitEmoji("🈶", "alphanum Japanese “not free of charge” button"),
    HabitEmoji("🈯", "alphanum Japanese “reserved” button"),
    HabitEmoji("🉐", "alphanum Japanese “bargain” button"),
    HabitEmoji("🈹", "alphanum Japanese “discount” button"),
    HabitEmoji("🈚", "alphanum Japanese “free of charge” button"),
    HabitEmoji("🈲", "alphanum Japanese “prohibited” button"),
    HabitEmoji("🉑", "alphanum Japanese “acceptable” button"),
    HabitEmoji("🈸", "alphanum Japanese “application” button"),
    HabitEmoji("🈴", "alphanum Japanese “passing grade” button"),
    HabitEmoji("🈳", "alphanum Japanese “vacancy” button"),
    HabitEmoji("㊗️", "alphanum Japanese “congratulations” button"),
    HabitEmoji("㊙️", "alphanum Japanese “secret” button"),
    HabitEmoji("🈺", "alphanum Japanese “open for business” button"),
    HabitEmoji("🈵", "alphanum Japanese “no vacancy” button"),
    HabitEmoji("🔴", "geometric red circle"),
    HabitEmoji("🟠", "geometric orange circle"),
    HabitEmoji("🟡", "geometric yellow circle"),
    HabitEmoji("🟢", "geometric green circle"),
    HabitEmoji("🔵", "geometric blue circle"),
    HabitEmoji("🟣", "geometric purple circle"),
    HabitEmoji("🟤", "geometric brown circle"),
    HabitEmoji("⚫", "geometric black circle"),
    HabitEmoji("⚪", "geometric white circle"),
    HabitEmoji("🟥", "geometric red square"),
    HabitEmoji("🟧", "geometric orange square"),
    HabitEmoji("🟨", "geometric yellow square"),
    HabitEmoji("🟩", "geometric green square"),
    HabitEmoji("🟦", "geometric blue square"),
    HabitEmoji("🟪", "geometric purple square"),
    HabitEmoji("🟫", "geometric brown square"),
    HabitEmoji("⬛", "geometric black large square"),
    HabitEmoji("⬜", "geometric white large square"),
    HabitEmoji("◼️", "geometric black medium square"),
    HabitEmoji("◻️", "geometric white medium square"),
    HabitEmoji("◾", "geometric black medium-small square"),
    HabitEmoji("◽", "geometric white medium-small square"),
    HabitEmoji("▪️", "geometric black small square"),
    HabitEmoji("▫️", "geometric white small square"),
    HabitEmoji("🔶", "geometric large orange diamond"),
    HabitEmoji("🔷", "geometric large blue diamond"),
    HabitEmoji("🔸", "geometric small orange diamond"),
    HabitEmoji("🔹", "geometric small blue diamond"),
    HabitEmoji("🔺", "geometric red triangle pointed up"),
    HabitEmoji("🔻", "geometric red triangle pointed down"),
    HabitEmoji("💠", "geometric diamond with a dot"),
    HabitEmoji("🔘", "geometric radio button"),
    HabitEmoji("🔳", "geometric white square button"),
    HabitEmoji("🔲", "geometric black square button"),
  ]),
  HabitEmojiCategory("Flags", [
    HabitEmoji("🏁", "flag chequered flag"),
    HabitEmoji("🚩", "flag triangular flag"),
    HabitEmoji("🎌", "flag crossed flags"),
    HabitEmoji("🏴", "flag black flag"),
    HabitEmoji("🏳️", "flag white flag"),
    HabitEmoji("🏳️‍🌈", "flag rainbow flag"),
    HabitEmoji("🏳️‍⚧️", "flag transgender flag"),
    HabitEmoji("🏴‍☠️", "flag pirate flag"),
    HabitEmoji("🇦🇨", "country flag flag: Ascension Island"),
    HabitEmoji("🇦🇩", "country flag flag: Andorra"),
    HabitEmoji("🇦🇪", "country flag flag: United Arab Emirates"),
    HabitEmoji("🇦🇫", "country flag flag: Afghanistan"),
    HabitEmoji("🇦🇬", "country flag flag: Antigua & Barbuda"),
    HabitEmoji("🇦🇮", "country flag flag: Anguilla"),
    HabitEmoji("🇦🇱", "country flag flag: Albania"),
    HabitEmoji("🇦🇲", "country flag flag: Armenia"),
    HabitEmoji("🇦🇴", "country flag flag: Angola"),
    HabitEmoji("🇦🇶", "country flag flag: Antarctica"),
    HabitEmoji("🇦🇷", "country flag flag: Argentina"),
    HabitEmoji("🇦🇸", "country flag flag: American Samoa"),
    HabitEmoji("🇦🇹", "country flag flag: Austria"),
    HabitEmoji("🇦🇺", "country flag flag: Australia"),
    HabitEmoji("🇦🇼", "country flag flag: Aruba"),
    HabitEmoji("🇦🇽", "country flag flag: Åland Islands"),
    HabitEmoji("🇦🇿", "country flag flag: Azerbaijan"),
    HabitEmoji("🇧🇦", "country flag flag: Bosnia & Herzegovina"),
    HabitEmoji("🇧🇧", "country flag flag: Barbados"),
    HabitEmoji("🇧🇩", "country flag flag: Bangladesh"),
    HabitEmoji("🇧🇪", "country flag flag: Belgium"),
    HabitEmoji("🇧🇫", "country flag flag: Burkina Faso"),
    HabitEmoji("🇧🇬", "country flag flag: Bulgaria"),
    HabitEmoji("🇧🇭", "country flag flag: Bahrain"),
    HabitEmoji("🇧🇮", "country flag flag: Burundi"),
    HabitEmoji("🇧🇯", "country flag flag: Benin"),
    HabitEmoji("🇧🇱", "country flag flag: St. Barthélemy"),
    HabitEmoji("🇧🇲", "country flag flag: Bermuda"),
    HabitEmoji("🇧🇳", "country flag flag: Brunei"),
    HabitEmoji("🇧🇴", "country flag flag: Bolivia"),
    HabitEmoji("🇧🇶", "country flag flag: Caribbean Netherlands"),
    HabitEmoji("🇧🇷", "country flag flag: Brazil"),
    HabitEmoji("🇧🇸", "country flag flag: Bahamas"),
    HabitEmoji("🇧🇹", "country flag flag: Bhutan"),
    HabitEmoji("🇧🇻", "country flag flag: Bouvet Island"),
    HabitEmoji("🇧🇼", "country flag flag: Botswana"),
    HabitEmoji("🇧🇾", "country flag flag: Belarus"),
    HabitEmoji("🇧🇿", "country flag flag: Belize"),
    HabitEmoji("🇨🇦", "country flag flag: Canada"),
    HabitEmoji("🇨🇨", "country flag flag: Cocos (Keeling) Islands"),
    HabitEmoji("🇨🇩", "country flag flag: Congo - Kinshasa"),
    HabitEmoji("🇨🇫", "country flag flag: Central African Republic"),
    HabitEmoji("🇨🇬", "country flag flag: Congo - Brazzaville"),
    HabitEmoji("🇨🇭", "country flag flag: Switzerland"),
    HabitEmoji("🇨🇮", "country flag flag: Côte d’Ivoire"),
    HabitEmoji("🇨🇰", "country flag flag: Cook Islands"),
    HabitEmoji("🇨🇱", "country flag flag: Chile"),
    HabitEmoji("🇨🇲", "country flag flag: Cameroon"),
    HabitEmoji("🇨🇳", "country flag flag: China"),
    HabitEmoji("🇨🇴", "country flag flag: Colombia"),
    HabitEmoji("🇨🇵", "country flag flag: Clipperton Island"),
    HabitEmoji("🇨🇶", "country flag flag: Sark"),
    HabitEmoji("🇨🇷", "country flag flag: Costa Rica"),
    HabitEmoji("🇨🇺", "country flag flag: Cuba"),
    HabitEmoji("🇨🇻", "country flag flag: Cape Verde"),
    HabitEmoji("🇨🇼", "country flag flag: Curaçao"),
    HabitEmoji("🇨🇽", "country flag flag: Christmas Island"),
    HabitEmoji("🇨🇾", "country flag flag: Cyprus"),
    HabitEmoji("🇨🇿", "country flag flag: Czechia"),
    HabitEmoji("🇩🇪", "country flag flag: Germany"),
    HabitEmoji("🇩🇬", "country flag flag: Diego Garcia"),
    HabitEmoji("🇩🇯", "country flag flag: Djibouti"),
    HabitEmoji("🇩🇰", "country flag flag: Denmark"),
    HabitEmoji("🇩🇲", "country flag flag: Dominica"),
    HabitEmoji("🇩🇴", "country flag flag: Dominican Republic"),
    HabitEmoji("🇩🇿", "country flag flag: Algeria"),
    HabitEmoji("🇪🇦", "country flag flag: Ceuta & Melilla"),
    HabitEmoji("🇪🇨", "country flag flag: Ecuador"),
    HabitEmoji("🇪🇪", "country flag flag: Estonia"),
    HabitEmoji("🇪🇬", "country flag flag: Egypt"),
    HabitEmoji("🇪🇭", "country flag flag: Western Sahara"),
    HabitEmoji("🇪🇷", "country flag flag: Eritrea"),
    HabitEmoji("🇪🇸", "country flag flag: Spain"),
    HabitEmoji("🇪🇹", "country flag flag: Ethiopia"),
    HabitEmoji("🇪🇺", "country flag flag: European Union"),
    HabitEmoji("🇫🇮", "country flag flag: Finland"),
    HabitEmoji("🇫🇯", "country flag flag: Fiji"),
    HabitEmoji("🇫🇰", "country flag flag: Falkland Islands"),
    HabitEmoji("🇫🇲", "country flag flag: Micronesia"),
    HabitEmoji("🇫🇴", "country flag flag: Faroe Islands"),
    HabitEmoji("🇫🇷", "country flag flag: France"),
    HabitEmoji("🇬🇦", "country flag flag: Gabon"),
    HabitEmoji("🇬🇧", "country flag flag: United Kingdom"),
    HabitEmoji("🇬🇩", "country flag flag: Grenada"),
    HabitEmoji("🇬🇪", "country flag flag: Georgia"),
    HabitEmoji("🇬🇫", "country flag flag: French Guiana"),
    HabitEmoji("🇬🇬", "country flag flag: Guernsey"),
    HabitEmoji("🇬🇭", "country flag flag: Ghana"),
    HabitEmoji("🇬🇮", "country flag flag: Gibraltar"),
    HabitEmoji("🇬🇱", "country flag flag: Greenland"),
    HabitEmoji("🇬🇲", "country flag flag: Gambia"),
    HabitEmoji("🇬🇳", "country flag flag: Guinea"),
    HabitEmoji("🇬🇵", "country flag flag: Guadeloupe"),
    HabitEmoji("🇬🇶", "country flag flag: Equatorial Guinea"),
    HabitEmoji("🇬🇷", "country flag flag: Greece"),
    HabitEmoji(
        "🇬🇸", "country flag flag: South Georgia & South Sandwich Islands"),
    HabitEmoji("🇬🇹", "country flag flag: Guatemala"),
    HabitEmoji("🇬🇺", "country flag flag: Guam"),
    HabitEmoji("🇬🇼", "country flag flag: Guinea-Bissau"),
    HabitEmoji("🇬🇾", "country flag flag: Guyana"),
    HabitEmoji("🇭🇰", "country flag flag: Hong Kong SAR China"),
    HabitEmoji("🇭🇲", "country flag flag: Heard & McDonald Islands"),
    HabitEmoji("🇭🇳", "country flag flag: Honduras"),
    HabitEmoji("🇭🇷", "country flag flag: Croatia"),
    HabitEmoji("🇭🇹", "country flag flag: Haiti"),
    HabitEmoji("🇭🇺", "country flag flag: Hungary"),
    HabitEmoji("🇮🇨", "country flag flag: Canary Islands"),
    HabitEmoji("🇮🇩", "country flag flag: Indonesia"),
    HabitEmoji("🇮🇪", "country flag flag: Ireland"),
    HabitEmoji("🇮🇱", "country flag flag: Israel"),
    HabitEmoji("🇮🇲", "country flag flag: Isle of Man"),
    HabitEmoji("🇮🇳", "country flag flag: India"),
    HabitEmoji("🇮🇴", "country flag flag: British Indian Ocean Territory"),
    HabitEmoji("🇮🇶", "country flag flag: Iraq"),
    HabitEmoji("🇮🇷", "country flag flag: Iran"),
    HabitEmoji("🇮🇸", "country flag flag: Iceland"),
    HabitEmoji("🇮🇹", "country flag flag: Italy"),
    HabitEmoji("🇯🇪", "country flag flag: Jersey"),
    HabitEmoji("🇯🇲", "country flag flag: Jamaica"),
    HabitEmoji("🇯🇴", "country flag flag: Jordan"),
    HabitEmoji("🇯🇵", "country flag flag: Japan"),
    HabitEmoji("🇰🇪", "country flag flag: Kenya"),
    HabitEmoji("🇰🇬", "country flag flag: Kyrgyzstan"),
    HabitEmoji("🇰🇭", "country flag flag: Cambodia"),
    HabitEmoji("🇰🇮", "country flag flag: Kiribati"),
    HabitEmoji("🇰🇲", "country flag flag: Comoros"),
    HabitEmoji("🇰🇳", "country flag flag: St. Kitts & Nevis"),
    HabitEmoji("🇰🇵", "country flag flag: North Korea"),
    HabitEmoji("🇰🇷", "country flag flag: South Korea"),
    HabitEmoji("🇰🇼", "country flag flag: Kuwait"),
    HabitEmoji("🇰🇾", "country flag flag: Cayman Islands"),
    HabitEmoji("🇰🇿", "country flag flag: Kazakhstan"),
    HabitEmoji("🇱🇦", "country flag flag: Laos"),
    HabitEmoji("🇱🇧", "country flag flag: Lebanon"),
    HabitEmoji("🇱🇨", "country flag flag: St. Lucia"),
    HabitEmoji("🇱🇮", "country flag flag: Liechtenstein"),
    HabitEmoji("🇱🇰", "country flag flag: Sri Lanka"),
    HabitEmoji("🇱🇷", "country flag flag: Liberia"),
    HabitEmoji("🇱🇸", "country flag flag: Lesotho"),
    HabitEmoji("🇱🇹", "country flag flag: Lithuania"),
    HabitEmoji("🇱🇺", "country flag flag: Luxembourg"),
    HabitEmoji("🇱🇻", "country flag flag: Latvia"),
    HabitEmoji("🇱🇾", "country flag flag: Libya"),
    HabitEmoji("🇲🇦", "country flag flag: Morocco"),
    HabitEmoji("🇲🇨", "country flag flag: Monaco"),
    HabitEmoji("🇲🇩", "country flag flag: Moldova"),
    HabitEmoji("🇲🇪", "country flag flag: Montenegro"),
    HabitEmoji("🇲🇫", "country flag flag: St. Martin"),
    HabitEmoji("🇲🇬", "country flag flag: Madagascar"),
    HabitEmoji("🇲🇭", "country flag flag: Marshall Islands"),
    HabitEmoji("🇲🇰", "country flag flag: North Macedonia"),
    HabitEmoji("🇲🇱", "country flag flag: Mali"),
    HabitEmoji("🇲🇲", "country flag flag: Myanmar (Burma)"),
    HabitEmoji("🇲🇳", "country flag flag: Mongolia"),
    HabitEmoji("🇲🇴", "country flag flag: Macao SAR China"),
    HabitEmoji("🇲🇵", "country flag flag: Northern Mariana Islands"),
    HabitEmoji("🇲🇶", "country flag flag: Martinique"),
    HabitEmoji("🇲🇷", "country flag flag: Mauritania"),
    HabitEmoji("🇲🇸", "country flag flag: Montserrat"),
    HabitEmoji("🇲🇹", "country flag flag: Malta"),
    HabitEmoji("🇲🇺", "country flag flag: Mauritius"),
    HabitEmoji("🇲🇻", "country flag flag: Maldives"),
    HabitEmoji("🇲🇼", "country flag flag: Malawi"),
    HabitEmoji("🇲🇽", "country flag flag: Mexico"),
    HabitEmoji("🇲🇾", "country flag flag: Malaysia"),
    HabitEmoji("🇲🇿", "country flag flag: Mozambique"),
    HabitEmoji("🇳🇦", "country flag flag: Namibia"),
    HabitEmoji("🇳🇨", "country flag flag: New Caledonia"),
    HabitEmoji("🇳🇪", "country flag flag: Niger"),
    HabitEmoji("🇳🇫", "country flag flag: Norfolk Island"),
    HabitEmoji("🇳🇬", "country flag flag: Nigeria"),
    HabitEmoji("🇳🇮", "country flag flag: Nicaragua"),
    HabitEmoji("🇳🇱", "country flag flag: Netherlands"),
    HabitEmoji("🇳🇴", "country flag flag: Norway"),
    HabitEmoji("🇳🇵", "country flag flag: Nepal"),
    HabitEmoji("🇳🇷", "country flag flag: Nauru"),
    HabitEmoji("🇳🇺", "country flag flag: Niue"),
    HabitEmoji("🇳🇿", "country flag flag: New Zealand"),
    HabitEmoji("🇴🇲", "country flag flag: Oman"),
    HabitEmoji("🇵🇦", "country flag flag: Panama"),
    HabitEmoji("🇵🇪", "country flag flag: Peru"),
    HabitEmoji("🇵🇫", "country flag flag: French Polynesia"),
    HabitEmoji("🇵🇬", "country flag flag: Papua New Guinea"),
    HabitEmoji("🇵🇭", "country flag flag: Philippines"),
    HabitEmoji("🇵🇰", "country flag flag: Pakistan"),
    HabitEmoji("🇵🇱", "country flag flag: Poland"),
    HabitEmoji("🇵🇲", "country flag flag: St. Pierre & Miquelon"),
    HabitEmoji("🇵🇳", "country flag flag: Pitcairn Islands"),
    HabitEmoji("🇵🇷", "country flag flag: Puerto Rico"),
    HabitEmoji("🇵🇸", "country flag flag: Palestinian Territories"),
    HabitEmoji("🇵🇹", "country flag flag: Portugal"),
    HabitEmoji("🇵🇼", "country flag flag: Palau"),
    HabitEmoji("🇵🇾", "country flag flag: Paraguay"),
    HabitEmoji("🇶🇦", "country flag flag: Qatar"),
    HabitEmoji("🇷🇪", "country flag flag: Réunion"),
    HabitEmoji("🇷🇴", "country flag flag: Romania"),
    HabitEmoji("🇷🇸", "country flag flag: Serbia"),
    HabitEmoji("🇷🇺", "country flag flag: Russia"),
    HabitEmoji("🇷🇼", "country flag flag: Rwanda"),
    HabitEmoji("🇸🇦", "country flag flag: Saudi Arabia"),
    HabitEmoji("🇸🇧", "country flag flag: Solomon Islands"),
    HabitEmoji("🇸🇨", "country flag flag: Seychelles"),
    HabitEmoji("🇸🇩", "country flag flag: Sudan"),
    HabitEmoji("🇸🇪", "country flag flag: Sweden"),
    HabitEmoji("🇸🇬", "country flag flag: Singapore"),
    HabitEmoji("🇸🇭", "country flag flag: St. Helena"),
    HabitEmoji("🇸🇮", "country flag flag: Slovenia"),
    HabitEmoji("🇸🇯", "country flag flag: Svalbard & Jan Mayen"),
    HabitEmoji("🇸🇰", "country flag flag: Slovakia"),
    HabitEmoji("🇸🇱", "country flag flag: Sierra Leone"),
    HabitEmoji("🇸🇲", "country flag flag: San Marino"),
    HabitEmoji("🇸🇳", "country flag flag: Senegal"),
    HabitEmoji("🇸🇴", "country flag flag: Somalia"),
    HabitEmoji("🇸🇷", "country flag flag: Suriname"),
    HabitEmoji("🇸🇸", "country flag flag: South Sudan"),
    HabitEmoji("🇸🇹", "country flag flag: São Tomé & Príncipe"),
    HabitEmoji("🇸🇻", "country flag flag: El Salvador"),
    HabitEmoji("🇸🇽", "country flag flag: Sint Maarten"),
    HabitEmoji("🇸🇾", "country flag flag: Syria"),
    HabitEmoji("🇸🇿", "country flag flag: Eswatini"),
    HabitEmoji("🇹🇦", "country flag flag: Tristan da Cunha"),
    HabitEmoji("🇹🇨", "country flag flag: Turks & Caicos Islands"),
    HabitEmoji("🇹🇩", "country flag flag: Chad"),
    HabitEmoji("🇹🇫", "country flag flag: French Southern Territories"),
    HabitEmoji("🇹🇬", "country flag flag: Togo"),
    HabitEmoji("🇹🇭", "country flag flag: Thailand"),
    HabitEmoji("🇹🇯", "country flag flag: Tajikistan"),
    HabitEmoji("🇹🇰", "country flag flag: Tokelau"),
    HabitEmoji("🇹🇱", "country flag flag: Timor-Leste"),
    HabitEmoji("🇹🇲", "country flag flag: Turkmenistan"),
    HabitEmoji("🇹🇳", "country flag flag: Tunisia"),
    HabitEmoji("🇹🇴", "country flag flag: Tonga"),
    HabitEmoji("🇹🇷", "country flag flag: Türkiye"),
    HabitEmoji("🇹🇹", "country flag flag: Trinidad & Tobago"),
    HabitEmoji("🇹🇻", "country flag flag: Tuvalu"),
    HabitEmoji("🇹🇼", "country flag flag: Taiwan"),
    HabitEmoji("🇹🇿", "country flag flag: Tanzania"),
    HabitEmoji("🇺🇦", "country flag flag: Ukraine"),
    HabitEmoji("🇺🇬", "country flag flag: Uganda"),
    HabitEmoji("🇺🇲", "country flag flag: U.S. Outlying Islands"),
    HabitEmoji("🇺🇳", "country flag flag: United Nations"),
    HabitEmoji("🇺🇸", "country flag flag: United States"),
    HabitEmoji("🇺🇾", "country flag flag: Uruguay"),
    HabitEmoji("🇺🇿", "country flag flag: Uzbekistan"),
    HabitEmoji("🇻🇦", "country flag flag: Vatican City"),
    HabitEmoji("🇻🇨", "country flag flag: St. Vincent & Grenadines"),
    HabitEmoji("🇻🇪", "country flag flag: Venezuela"),
    HabitEmoji("🇻🇬", "country flag flag: British Virgin Islands"),
    HabitEmoji("🇻🇮", "country flag flag: U.S. Virgin Islands"),
    HabitEmoji("🇻🇳", "country flag flag: Vietnam"),
    HabitEmoji("🇻🇺", "country flag flag: Vanuatu"),
    HabitEmoji("🇼🇫", "country flag flag: Wallis & Futuna"),
    HabitEmoji("🇼🇸", "country flag flag: Samoa"),
    HabitEmoji("🇽🇰", "country flag flag: Kosovo"),
    HabitEmoji("🇾🇪", "country flag flag: Yemen"),
    HabitEmoji("🇾🇹", "country flag flag: Mayotte"),
    HabitEmoji("🇿🇦", "country flag flag: South Africa"),
    HabitEmoji("🇿🇲", "country flag flag: Zambia"),
    HabitEmoji("🇿🇼", "country flag flag: Zimbabwe"),
    HabitEmoji("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "subdivision flag flag: England"),
    HabitEmoji("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "subdivision flag flag: Scotland"),
    HabitEmoji("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "subdivision flag flag: Wales"),
  ]),
];
